/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every verified recipe eligible for selection. */
        get: operations["listRecipes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/week/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the explicitly generated current week. */
        get: operations["getCurrentWeek"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/week/current/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or fully regenerate the current week. */
        post: operations["generateCurrentWeek"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/week/current/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append a specific verified recipe occurrence. */
        post: operations["addCurrentWeekRecipe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/week/current/recipes/{occurrenceID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                occurrenceID: components["parameters"]["OccurrenceID"];
            };
            cookie?: never;
        };
        get?: never;
        /** Replace one occurrence with a specific verified recipe. */
        put: operations["swapCurrentWeekRecipe"];
        post?: never;
        /** Remove one recipe occurrence. */
        delete: operations["removeCurrentWeekRecipe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/week/current/recipes/{occurrenceID}/random-swap": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                occurrenceID: components["parameters"]["OccurrenceID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace one occurrence with a random eligible recipe. */
        post: operations["randomSwapCurrentWeekRecipe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DurationRange: {
            minimumMinutes: number | null;
            maximumMinutes: number | null;
        };
        RecipeSummary: {
            id: number;
            key: string;
            name: string;
            /** Format: uri */
            imageUrl: string | null;
            yield: string | null;
            handsOn: components["schemas"]["DurationRange"];
            unattended: components["schemas"]["DurationRange"];
        };
        RecipeOccurrence: {
            id: number;
            position: number;
            recipe: components["schemas"]["RecipeSummary"];
        };
        Week: {
            id: number;
            /** Format: date */
            startsOn: string;
            recipes: components["schemas"]["RecipeOccurrence"][];
        };
        APIError: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description Canonical current week after the operation. */
        Week: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Week"];
            };
        };
        /** @description The path or JSON request was invalid. */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description The current week has not been explicitly generated. */
        NoCurrentWeek: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description The occurrence is not part of the current week. */
        OccurrenceNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description The requested week mutation could not be completed atomically. */
        WeekOperationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description The request could not be completed. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
    };
    parameters: {
        OccurrenceID: number;
    };
    requestBodies: {
        RecipeSelection: {
            content: {
                "application/json": {
                    recipeId: number;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRecipes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verified recipes ordered by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        recipes: components["schemas"]["RecipeSummary"][];
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getCurrentWeek: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Week"];
            404: components["responses"]["NoCurrentWeek"];
        };
    };
    generateCurrentWeek: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    recipeCount: number;
                };
            };
        };
        responses: {
            200: components["responses"]["Week"];
            400: components["responses"]["InvalidRequest"];
            422: components["responses"]["WeekOperationFailed"];
        };
    };
    addCurrentWeekRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RecipeSelection"];
        responses: {
            200: components["responses"]["Week"];
            400: components["responses"]["InvalidRequest"];
            404: components["responses"]["NoCurrentWeek"];
            422: components["responses"]["WeekOperationFailed"];
        };
    };
    swapCurrentWeekRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                occurrenceID: components["parameters"]["OccurrenceID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RecipeSelection"];
        responses: {
            200: components["responses"]["Week"];
            400: components["responses"]["InvalidRequest"];
            404: components["responses"]["OccurrenceNotFound"];
            422: components["responses"]["WeekOperationFailed"];
        };
    };
    removeCurrentWeekRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                occurrenceID: components["parameters"]["OccurrenceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Week"];
            400: components["responses"]["InvalidRequest"];
            404: components["responses"]["OccurrenceNotFound"];
            422: components["responses"]["WeekOperationFailed"];
        };
    };
    randomSwapCurrentWeekRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                occurrenceID: components["parameters"]["OccurrenceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Week"];
            400: components["responses"]["InvalidRequest"];
            404: components["responses"]["OccurrenceNotFound"];
            422: components["responses"]["WeekOperationFailed"];
        };
    };
}
