-- +goose Up
CREATE TABLE catalog_applied_releases (
    release_id TEXT PRIMARY KEY CHECK (release_id <> '' AND release_id = lower(release_id)),
    release_digest TEXT NOT NULL CHECK (release_digest ~ '^sha256:[0-9a-f]{64}$'),
    manifest JSONB NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE catalog_recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE CHECK (key <> '' AND key = lower(key)),
    name TEXT NOT NULL CHECK (trim(name) <> ''),
    status TEXT NOT NULL CHECK (status IN ('reviewable', 'verified')),
    recipe_document JSONB NOT NULL,
    source_identity JSONB NOT NULL,
    semantic_profile JSONB NOT NULL DEFAULT '{}'::JSONB,
    source_url TEXT CHECK (source_url IS NULL OR trim(source_url) <> ''),
    source_attribution TEXT NOT NULL CHECK (trim(source_attribution) <> ''),
    document_digest TEXT NOT NULL UNIQUE CHECK (document_digest ~ '^sha256:[0-9a-f]{64}$'),
    source_identity_digest TEXT NOT NULL UNIQUE CHECK (source_identity_digest ~ '^sha256:[0-9a-f]{64}$'),
    selected_recipe_digest TEXT NOT NULL UNIQUE CHECK (selected_recipe_digest ~ '^sha256:[0-9a-f]{64}$'),
    release_id TEXT NOT NULL REFERENCES catalog_applied_releases(release_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    release_digest TEXT NOT NULL CHECK (release_digest ~ '^sha256:[0-9a-f]{64}$'),
    published_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX catalog_recipes_verified_name_idx ON catalog_recipes(name) WHERE status = 'verified';
CREATE INDEX catalog_recipes_document_gin_idx ON catalog_recipes USING GIN (recipe_document);
CREATE INDEX catalog_recipes_profile_gin_idx ON catalog_recipes USING GIN (semantic_profile);

CREATE TABLE household_catalog_memberships (
    household_id UUID NOT NULL REFERENCES households(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    catalog_recipe_id BIGINT NOT NULL REFERENCES catalog_recipes(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    materialized_recipe_id BIGINT NOT NULL,
    state TEXT NOT NULL CHECK (state IN ('trial', 'adopted')),
    catalog_document_digest TEXT NOT NULL CHECK (catalog_document_digest ~ '^sha256:[0-9a-f]{64}$'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (household_id, catalog_recipe_id),
    UNIQUE (household_id, materialized_recipe_id),
    FOREIGN KEY (household_id, materialized_recipe_id) REFERENCES recipes(household_id, id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

-- +goose StatementBegin
CREATE FUNCTION require_verified_catalog_membership() RETURNS TRIGGER AS $$
DECLARE
    current_status TEXT;
    current_digest TEXT;
BEGIN
    SELECT status, document_digest INTO current_status, current_digest
    FROM catalog_recipes WHERE id = NEW.catalog_recipe_id;
    IF current_status <> 'verified' THEN
        RAISE EXCEPTION 'catalog membership requires a verified catalog recipe';
    END IF;
    IF NEW.catalog_document_digest <> current_digest THEN
        RAISE EXCEPTION 'catalog membership digest must match catalog recipe';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER household_catalog_memberships_require_verified
BEFORE INSERT OR UPDATE OF catalog_recipe_id, catalog_document_digest ON household_catalog_memberships
FOR EACH ROW EXECUTE FUNCTION require_verified_catalog_membership();

-- +goose Down
DROP TRIGGER IF EXISTS household_catalog_memberships_require_verified ON household_catalog_memberships;
DROP FUNCTION IF EXISTS require_verified_catalog_membership();
DROP TABLE IF EXISTS household_catalog_memberships;
DROP INDEX IF EXISTS catalog_recipes_profile_gin_idx;
DROP INDEX IF EXISTS catalog_recipes_document_gin_idx;
DROP INDEX IF EXISTS catalog_recipes_verified_name_idx;
DROP TABLE IF EXISTS catalog_recipes;
DROP TABLE IF EXISTS catalog_applied_releases;
