-- +goose Up
CREATE TABLE store_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE CHECK (key <> '' AND key = lower(key)),
    name TEXT NOT NULL UNIQUE CHECK (trim(name) <> '')
);

-- Manual grocery lines are assigned to this built-in section.
INSERT INTO store_sections (key, name) VALUES ('other', 'Other');

CREATE TABLE units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE CHECK (key <> '' AND key = lower(key)),
    name TEXT NOT NULL CHECK (trim(name) <> ''),
    symbol TEXT NOT NULL CHECK (trim(symbol) <> ''),
    dimension TEXT NOT NULL CHECK (dimension IN ('count', 'mass', 'volume')),
    to_base_numerator BIGINT NOT NULL CHECK (to_base_numerator > 0),
    to_base_denominator BIGINT NOT NULL CHECK (to_base_denominator > 0),
    UNIQUE (dimension, name)
);

-- Exact conversion ratios. Volume is based on US teaspoons; mass is based on ounces.
INSERT INTO units (key, name, symbol, dimension, to_base_numerator, to_base_denominator) VALUES
    ('each', 'each', 'each', 'count', 1, 1),
    ('slice', 'slice', 'slices', 'count', 1, 1),
    ('clove', 'clove', 'cloves', 'count', 1, 1),
    ('leaf', 'leaf', 'leaves', 'count', 1, 1),
    ('bunch', 'bunch', 'bunches', 'count', 1, 1),
    ('sprig', 'sprig', 'sprigs', 'count', 1, 1),
    ('tsp', 'teaspoon', 'tsp', 'volume', 1, 1),
    ('tbsp', 'tablespoon', 'tbsp', 'volume', 3, 1),
    ('floz', 'fluid ounce', 'fl oz', 'volume', 6, 1),
    ('cup', 'cup', 'cup', 'volume', 48, 1),
    ('pint', 'pint', 'pt', 'volume', 96, 1),
    ('quart', 'quart', 'qt', 'volume', 192, 1),
    ('gallon', 'gallon', 'gal', 'volume', 768, 1),
    ('ml', 'milliliter', 'mL', 'volume', 32000000, 157725491),
    ('l', 'liter', 'L', 'volume', 32000000000, 157725491),
    ('oz', 'ounce', 'oz', 'mass', 1, 1),
    ('lb', 'pound', 'lb', 'mass', 16, 1),
    ('g', 'gram', 'g', 'mass', 1600000, 45359237),
    ('kg', 'kilogram', 'kg', 'mass', 1600000000, 45359237);

CREATE TABLE grocery_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE CHECK (key <> '' AND key = lower(key)),
    name TEXT NOT NULL UNIQUE CHECK (trim(name) <> ''),
    store_section_id BIGINT NOT NULL REFERENCES store_sections(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    shopping_mode TEXT NOT NULL CHECK (shopping_mode IN ('measured', 'counted', 'presence-only')),
    created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
    updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE CHECK (key <> '' AND key = lower(key)),
    name TEXT NOT NULL UNIQUE CHECK (trim(name) <> ''),
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'reviewable', 'verified')),
    image_url TEXT,
    yield_text TEXT,
    hands_on_min_minutes BIGINT,
    hands_on_max_minutes BIGINT,
    unattended_min_minutes BIGINT,
    unattended_max_minutes BIGINT,
    verified_at TEXT,
    created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
    updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
    CHECK (image_url IS NULL OR trim(image_url) <> ''),
    CHECK (yield_text IS NULL OR trim(yield_text) <> ''),
    CHECK (
        (hands_on_min_minutes IS NULL AND hands_on_max_minutes IS NULL)
        OR (hands_on_min_minutes >= 0 AND hands_on_max_minutes >= hands_on_min_minutes)
    ),
    CHECK (
        (unattended_min_minutes IS NULL AND unattended_max_minutes IS NULL)
        OR (unattended_min_minutes >= 0 AND unattended_max_minutes >= unattended_min_minutes)
    ),
    CHECK (
        (status = 'verified' AND verified_at IS NOT NULL)
        OR (status <> 'verified' AND verified_at IS NULL)
    )
);

CREATE TABLE recipe_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    relationship TEXT NOT NULL CHECK (relationship IN ('source', 'adapted-from')),
    attribution TEXT NOT NULL CHECK (trim(attribution) <> ''),
    url TEXT CHECK (url IS NULL OR trim(url) <> ''),
    checked_on TEXT CHECK (checked_on IS NULL OR checked_on ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'),
    is_primary BIGINT NOT NULL DEFAULT 0 CHECK (is_primary IN (0, 1)),
    position BIGINT NOT NULL CHECK (position >= 0),
    UNIQUE (recipe_id, position)
);

CREATE UNIQUE INDEX one_primary_source_per_recipe
    ON recipe_sources(recipe_id)
    WHERE is_primary = 1;

CREATE TABLE recipe_ingredient_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (trim(name) <> ''),
    position BIGINT NOT NULL CHECK (position >= 0),
    UNIQUE (recipe_id, position)
);

CREATE TABLE recipe_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL REFERENCES recipe_ingredient_sections(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    grocery_item_id BIGINT REFERENCES grocery_items(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    position BIGINT NOT NULL CHECK (position >= 0),
    source_text TEXT NOT NULL CHECK (trim(source_text) <> ''),
    quantity_kind TEXT NOT NULL CHECK (quantity_kind IN ('exact', 'range', 'unspecified')),
    amount_min_numerator BIGINT,
    amount_min_denominator BIGINT,
    amount_max_numerator BIGINT,
    amount_max_denominator BIGINT,
    unit_id BIGINT REFERENCES units(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    package_type TEXT CHECK (package_type IS NULL OR trim(package_type) <> ''),
    package_size_numerator BIGINT,
    package_size_denominator BIGINT,
    package_size_unit_id BIGINT REFERENCES units(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    preparation TEXT CHECK (preparation IS NULL OR trim(preparation) <> ''),
    is_optional BIGINT NOT NULL DEFAULT 0 CHECK (is_optional IN (0, 1)),
    include_on_grocery_list BIGINT NOT NULL DEFAULT 1 CHECK (include_on_grocery_list IN (0, 1)),
    display_note TEXT CHECK (display_note IS NULL OR trim(display_note) <> ''),
    UNIQUE (section_id, position),
    CHECK (
        (quantity_kind = 'unspecified'
            AND amount_min_numerator IS NULL
            AND amount_min_denominator IS NULL
            AND amount_max_numerator IS NULL
            AND amount_max_denominator IS NULL
            AND unit_id IS NULL
            AND package_type IS NULL
            AND package_size_numerator IS NULL
            AND package_size_denominator IS NULL
            AND package_size_unit_id IS NULL)
        OR
        (quantity_kind = 'exact'
            AND amount_min_numerator IS NOT NULL
            AND amount_min_numerator >= 0
            AND amount_min_denominator IS NOT NULL
            AND amount_min_denominator > 0
            AND amount_max_numerator IS NULL
            AND amount_max_denominator IS NULL
            AND ((unit_id IS NOT NULL AND package_type IS NULL)
                OR (unit_id IS NULL AND package_type IS NOT NULL)))
        OR
        (quantity_kind = 'range'
            AND amount_min_numerator IS NOT NULL
            AND amount_min_numerator >= 0
            AND amount_min_denominator IS NOT NULL
            AND amount_min_denominator > 0
            AND amount_max_numerator IS NOT NULL
            AND amount_max_numerator >= 0
            AND amount_max_denominator IS NOT NULL
            AND amount_max_denominator > 0
            AND (amount_min_numerator * amount_max_denominator)
                <= (amount_max_numerator * amount_min_denominator)
            AND ((unit_id IS NOT NULL AND package_type IS NULL)
                OR (unit_id IS NULL AND package_type IS NOT NULL)))
    ),
    CHECK (
        (package_type IS NULL
            AND package_size_numerator IS NULL
            AND package_size_denominator IS NULL
            AND package_size_unit_id IS NULL)
        OR
        (package_type IS NOT NULL
            AND ((package_size_numerator IS NULL
                    AND package_size_denominator IS NULL
                    AND package_size_unit_id IS NULL)
                OR (package_size_numerator IS NOT NULL
                    AND package_size_numerator > 0
                    AND package_size_denominator IS NOT NULL
                    AND package_size_denominator > 0
                    AND package_size_unit_id IS NOT NULL)))
    )
);

CREATE TABLE recipe_instruction_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (trim(name) <> ''),
    position BIGINT NOT NULL CHECK (position >= 0),
    UNIQUE (recipe_id, position)
);

CREATE TABLE recipe_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL REFERENCES recipe_instruction_sections(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    position BIGINT NOT NULL CHECK (position >= 0),
    instruction TEXT NOT NULL CHECK (trim(instruction) <> ''),
    UNIQUE (section_id, position)
);

CREATE TABLE recipe_review_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    field_path TEXT NOT NULL CHECK (trim(field_path) <> ''),
    kind TEXT NOT NULL CHECK (kind IN ('backfilled', 'rewritten', 'conflict-resolved')),
    note TEXT NOT NULL CHECK (trim(note) <> ''),
    approved BIGINT NOT NULL DEFAULT 0 CHECK (approved IN (0, 1)),
    UNIQUE (recipe_id, field_path, kind)
);

CREATE TABLE weeks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    starts_on TEXT NOT NULL UNIQUE
        CHECK (starts_on ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
        CHECK (to_date(starts_on, 'YYYY-MM-DD')::TEXT = starts_on)
        CHECK (EXTRACT(DOW FROM to_date(starts_on, 'YYYY-MM-DD')) = 0),
    created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
    updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE week_recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_id BIGINT NOT NULL REFERENCES weeks(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    position BIGINT NOT NULL CHECK (position >= 0),
    created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
    UNIQUE (week_id, position)
);

CREATE TABLE shopping_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_id BIGINT NOT NULL UNIQUE REFERENCES weeks(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
    updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE shopping_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_list_id BIGINT NOT NULL REFERENCES shopping_lists(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    grocery_item_id BIGINT REFERENCES grocery_items(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    store_section_id BIGINT NOT NULL REFERENCES store_sections(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    aggregation_key TEXT,
    origin TEXT NOT NULL CHECK (origin IN ('generated', 'manual')),
    display_name TEXT NOT NULL CHECK (trim(display_name) <> ''),
    quantity_kind TEXT NOT NULL CHECK (quantity_kind IN ('exact', 'range', 'unspecified', 'presence')),
    amount_min_numerator BIGINT,
    amount_min_denominator BIGINT,
    amount_max_numerator BIGINT,
    amount_max_denominator BIGINT,
    unit_id BIGINT REFERENCES units(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    package_type TEXT,
    package_size_numerator BIGINT,
    package_size_denominator BIGINT,
    package_size_unit_id BIGINT REFERENCES units(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    is_optional BIGINT NOT NULL DEFAULT 0 CHECK (is_optional IN (0, 1)),
    is_removed BIGINT NOT NULL DEFAULT 0 CHECK (is_removed IN (0, 1)),
    is_completed BIGINT NOT NULL DEFAULT 0 CHECK (is_completed IN (0, 1)),
    display_position BIGINT NOT NULL CHECK (display_position >= 0),
    override_text TEXT CHECK (override_text IS NULL OR trim(override_text) <> ''),
    created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
    updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
    UNIQUE (shopping_list_id, aggregation_key),
    CHECK ((origin = 'generated' AND grocery_item_id IS NOT NULL AND aggregation_key IS NOT NULL)
        OR (origin = 'manual' AND grocery_item_id IS NULL AND aggregation_key IS NULL)),
    CHECK (
        (quantity_kind IN ('unspecified', 'presence')
            AND amount_min_numerator IS NULL AND amount_min_denominator IS NULL
            AND amount_max_numerator IS NULL AND amount_max_denominator IS NULL
            AND unit_id IS NULL AND package_type IS NULL
            AND package_size_numerator IS NULL AND package_size_denominator IS NULL
            AND package_size_unit_id IS NULL)
        OR (quantity_kind = 'exact'
            AND amount_min_numerator IS NOT NULL AND amount_min_numerator >= 0
            AND amount_min_denominator IS NOT NULL AND amount_min_denominator > 0
            AND amount_max_numerator IS NULL AND amount_max_denominator IS NULL
            AND ((unit_id IS NOT NULL AND package_type IS NULL)
                OR (unit_id IS NULL AND package_type IS NOT NULL)))
        OR (quantity_kind = 'range'
            AND amount_min_numerator IS NOT NULL AND amount_min_numerator >= 0
            AND amount_min_denominator IS NOT NULL AND amount_min_denominator > 0
            AND amount_max_numerator IS NOT NULL AND amount_max_numerator >= 0
            AND amount_max_denominator IS NOT NULL AND amount_max_denominator > 0
            AND (amount_min_numerator * amount_max_denominator)
                <= (amount_max_numerator * amount_min_denominator)
            AND ((unit_id IS NOT NULL AND package_type IS NULL)
                OR (unit_id IS NULL AND package_type IS NOT NULL)))
    ),
    CHECK (
        (package_type IS NULL AND package_size_numerator IS NULL
            AND package_size_denominator IS NULL AND package_size_unit_id IS NULL)
        OR (package_type IS NOT NULL
            AND ((package_size_numerator IS NULL AND package_size_denominator IS NULL
                    AND package_size_unit_id IS NULL)
                OR (package_size_numerator IS NOT NULL AND package_size_numerator > 0
                    AND package_size_denominator IS NOT NULL AND package_size_denominator > 0
                    AND package_size_unit_id IS NOT NULL)))
    )
);

CREATE TABLE shopping_line_contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_line_id BIGINT NOT NULL REFERENCES shopping_lines(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    week_recipe_id BIGINT NOT NULL REFERENCES week_recipes(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    recipe_ingredient_id BIGINT NOT NULL REFERENCES recipe_ingredients(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    quantity_kind TEXT NOT NULL CHECK (quantity_kind IN ('exact', 'range', 'unspecified')),
    amount_min_numerator BIGINT,
    amount_min_denominator BIGINT,
    amount_max_numerator BIGINT,
    amount_max_denominator BIGINT,
    unit_id BIGINT REFERENCES units(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    package_type TEXT,
    package_size_numerator BIGINT,
    package_size_denominator BIGINT,
    package_size_unit_id BIGINT REFERENCES units(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    is_optional BIGINT NOT NULL CHECK (is_optional IN (0, 1)),
    UNIQUE (shopping_line_id, week_recipe_id, recipe_ingredient_id),
    CHECK (
        (quantity_kind = 'unspecified'
            AND amount_min_numerator IS NULL AND amount_min_denominator IS NULL
            AND amount_max_numerator IS NULL AND amount_max_denominator IS NULL
            AND unit_id IS NULL AND package_type IS NULL
            AND package_size_numerator IS NULL AND package_size_denominator IS NULL
            AND package_size_unit_id IS NULL)
        OR (quantity_kind = 'exact'
            AND amount_min_numerator IS NOT NULL AND amount_min_numerator >= 0
            AND amount_min_denominator IS NOT NULL AND amount_min_denominator > 0
            AND amount_max_numerator IS NULL AND amount_max_denominator IS NULL
            AND ((unit_id IS NOT NULL AND package_type IS NULL)
                OR (unit_id IS NULL AND package_type IS NOT NULL)))
        OR (quantity_kind = 'range'
            AND amount_min_numerator IS NOT NULL AND amount_min_numerator >= 0
            AND amount_min_denominator IS NOT NULL AND amount_min_denominator > 0
            AND amount_max_numerator IS NOT NULL AND amount_max_numerator >= 0
            AND amount_max_denominator IS NOT NULL AND amount_max_denominator > 0
            AND (amount_min_numerator * amount_max_denominator)
                <= (amount_max_numerator * amount_min_denominator)
            AND ((unit_id IS NOT NULL AND package_type IS NULL)
                OR (unit_id IS NULL AND package_type IS NOT NULL)))
    ),
    CHECK (
        (package_type IS NULL AND package_size_numerator IS NULL
            AND package_size_denominator IS NULL AND package_size_unit_id IS NULL)
        OR (package_type IS NOT NULL
            AND ((package_size_numerator IS NULL AND package_size_denominator IS NULL
                    AND package_size_unit_id IS NULL)
                OR (package_size_numerator IS NOT NULL AND package_size_numerator > 0
                    AND package_size_denominator IS NOT NULL AND package_size_denominator > 0
                    AND package_size_unit_id IS NOT NULL)))
    )
);

CREATE INDEX week_recipes_recipe_id_idx ON week_recipes(recipe_id);
CREATE INDEX shopping_lines_section_idx ON shopping_lines(shopping_list_id, store_section_id, display_position);
CREATE INDEX shopping_contributions_occurrence_idx ON shopping_line_contributions(week_recipe_id);

-- Trigger helpers preserve the corpus and shopping-list invariants in PostgreSQL.
-- +goose StatementBegin
CREATE FUNCTION require_verified_week_recipe() RETURNS TRIGGER AS $$
BEGIN
    IF coalesce((SELECT status FROM recipes WHERE id = NEW.recipe_id), '') <> 'verified' THEN
        RAISE EXCEPTION 'week recipe must reference a verified recipe';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER week_recipes_require_verified_recipe
BEFORE INSERT OR UPDATE OF recipe_id ON week_recipes
FOR EACH ROW EXECUTE FUNCTION require_verified_week_recipe();

-- +goose StatementBegin
CREATE FUNCTION require_matching_contribution() RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM shopping_lines sl
        JOIN shopping_lists list ON list.id = sl.shopping_list_id
        JOIN week_recipes wr ON wr.id = NEW.week_recipe_id AND wr.week_id = list.week_id
        JOIN recipe_ingredient_sections ris ON ris.recipe_id = wr.recipe_id
        JOIN recipe_ingredients ri ON ri.section_id = ris.id AND ri.id = NEW.recipe_ingredient_id
        WHERE sl.id = NEW.shopping_line_id AND sl.origin = 'generated'
          AND sl.grocery_item_id = ri.grocery_item_id
    ) THEN
        RAISE EXCEPTION 'contribution must match its line, week occurrence, and recipe ingredient';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER shopping_contributions_require_matching_recipe
BEFORE INSERT OR UPDATE ON shopping_line_contributions
FOR EACH ROW EXECUTE FUNCTION require_matching_contribution();

-- +goose StatementBegin
CREATE FUNCTION enforce_recipe_lifecycle() RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'draft' OR NEW.verified_at IS NOT NULL THEN
            RAISE EXCEPTION 'new recipe must start as draft';
        END IF;
        RETURN NEW;
    END IF;

    IF OLD.status = 'verified' AND NEW.status = 'verified' THEN
        RAISE EXCEPTION 'return recipe to draft before editing';
    END IF;

    IF NEW.status = 'verified' AND OLD.status <> 'verified' THEN
        IF OLD.status <> 'reviewable' THEN
            RAISE EXCEPTION 'recipe must be reviewable before verification';
        ELSIF NEW.verified_at IS NULL THEN
            RAISE EXCEPTION 'verified recipe requires verified_at';
        ELSIF (SELECT count(*) FROM recipe_sources WHERE recipe_id = NEW.id AND is_primary = 1) <> 1 THEN
            RAISE EXCEPTION 'verified recipe requires exactly one primary source';
        ELSIF NOT EXISTS (SELECT 1 FROM recipe_ingredient_sections WHERE recipe_id = NEW.id) THEN
            RAISE EXCEPTION 'verified recipe requires an ingredient section';
        ELSIF NOT EXISTS (
            SELECT 1 FROM recipe_ingredients ri
            JOIN recipe_ingredient_sections ris ON ris.id = ri.section_id
            WHERE ris.recipe_id = NEW.id
        ) THEN
            RAISE EXCEPTION 'verified recipe requires ingredients';
        ELSIF EXISTS (
            SELECT 1 FROM recipe_ingredients ri
            JOIN recipe_ingredient_sections ris ON ris.id = ri.section_id
            WHERE ris.recipe_id = NEW.id AND ri.grocery_item_id IS NULL
        ) THEN
            RAISE EXCEPTION 'verified recipe has an unmapped ingredient';
        ELSIF NOT EXISTS (
            SELECT 1 FROM recipe_steps rs
            JOIN recipe_instruction_sections rxs ON rxs.id = rs.section_id
            WHERE rxs.recipe_id = NEW.id
        ) THEN
            RAISE EXCEPTION 'verified recipe requires instructions';
        ELSIF EXISTS (SELECT 1 FROM recipe_review_flags WHERE recipe_id = NEW.id AND approved = 0) THEN
            RAISE EXCEPTION 'verified recipe has unapproved review flags';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER enforce_recipe_lifecycle
BEFORE INSERT OR UPDATE ON recipes
FOR EACH ROW EXECUTE FUNCTION enforce_recipe_lifecycle();

-- +goose StatementBegin
CREATE FUNCTION protect_verified_recipe_child() RETURNS TRIGGER AS $$
DECLARE
    recipe_status TEXT;
BEGIN
    IF TG_TABLE_NAME IN ('recipe_sources', 'recipe_ingredient_sections', 'recipe_instruction_sections', 'recipe_review_flags') THEN
        SELECT status INTO recipe_status FROM recipes
        WHERE id = CASE WHEN TG_OP = 'INSERT' THEN NEW.recipe_id ELSE OLD.recipe_id END;
    ELSIF TG_TABLE_NAME = 'recipe_ingredients' THEN
        SELECT r.status INTO recipe_status FROM recipes r
        JOIN recipe_ingredient_sections s ON s.recipe_id = r.id
        WHERE s.id = CASE WHEN TG_OP = 'INSERT' THEN NEW.section_id ELSE OLD.section_id END;
    ELSIF TG_TABLE_NAME = 'recipe_steps' THEN
        SELECT r.status INTO recipe_status FROM recipes r
        JOIN recipe_instruction_sections s ON s.recipe_id = r.id
        WHERE s.id = CASE WHEN TG_OP = 'INSERT' THEN NEW.section_id ELSE OLD.section_id END;
    END IF;

    IF recipe_status = 'verified' THEN
        RAISE EXCEPTION 'return recipe to draft before editing %',
            CASE TG_TABLE_NAME
                WHEN 'recipe_sources' THEN 'sources'
                WHEN 'recipe_review_flags' THEN 'review flags'
                WHEN 'recipe_instruction_sections' THEN 'instructions'
                WHEN 'recipe_steps' THEN 'instructions'
                ELSE 'ingredients'
            END;
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER protect_verified_recipe_sources
BEFORE INSERT OR UPDATE OR DELETE ON recipe_sources
FOR EACH ROW EXECUTE FUNCTION protect_verified_recipe_child();
CREATE TRIGGER protect_verified_ingredient_sections
BEFORE INSERT OR UPDATE OR DELETE ON recipe_ingredient_sections
FOR EACH ROW EXECUTE FUNCTION protect_verified_recipe_child();
CREATE TRIGGER protect_verified_ingredients
BEFORE INSERT OR UPDATE OR DELETE ON recipe_ingredients
FOR EACH ROW EXECUTE FUNCTION protect_verified_recipe_child();
CREATE TRIGGER protect_verified_instruction_sections
BEFORE INSERT OR UPDATE OR DELETE ON recipe_instruction_sections
FOR EACH ROW EXECUTE FUNCTION protect_verified_recipe_child();
CREATE TRIGGER protect_verified_steps
BEFORE INSERT OR UPDATE OR DELETE ON recipe_steps
FOR EACH ROW EXECUTE FUNCTION protect_verified_recipe_child();
CREATE TRIGGER protect_verified_review_flags
BEFORE INSERT OR UPDATE OR DELETE ON recipe_review_flags
FOR EACH ROW EXECUTE FUNCTION protect_verified_recipe_child();

-- +goose Down
DROP TRIGGER IF EXISTS protect_verified_review_flags ON recipe_review_flags;
DROP TRIGGER IF EXISTS protect_verified_steps ON recipe_steps;
DROP TRIGGER IF EXISTS protect_verified_instruction_sections ON recipe_instruction_sections;
DROP TRIGGER IF EXISTS protect_verified_ingredients ON recipe_ingredients;
DROP TRIGGER IF EXISTS protect_verified_ingredient_sections ON recipe_ingredient_sections;
DROP TRIGGER IF EXISTS protect_verified_recipe_sources ON recipe_sources;
DROP FUNCTION IF EXISTS protect_verified_recipe_child();
DROP TRIGGER IF EXISTS enforce_recipe_lifecycle ON recipes;
DROP FUNCTION IF EXISTS enforce_recipe_lifecycle();
DROP TRIGGER IF EXISTS shopping_contributions_require_matching_recipe ON shopping_line_contributions;
DROP FUNCTION IF EXISTS require_matching_contribution();
DROP TRIGGER IF EXISTS week_recipes_require_verified_recipe ON week_recipes;
DROP FUNCTION IF EXISTS require_verified_week_recipe();
DROP TABLE IF EXISTS shopping_line_contributions;
DROP TABLE IF EXISTS shopping_lines;
DROP TABLE IF EXISTS shopping_lists;
DROP TABLE IF EXISTS week_recipes;
DROP TABLE IF EXISTS weeks;
DROP TABLE IF EXISTS recipe_review_flags;
DROP TABLE IF EXISTS recipe_steps;
DROP TABLE IF EXISTS recipe_instruction_sections;
DROP TABLE IF EXISTS recipe_ingredients;
DROP TABLE IF EXISTS recipe_ingredient_sections;
DROP INDEX IF EXISTS one_primary_source_per_recipe;
DROP TABLE IF EXISTS recipe_sources;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS grocery_items;
DROP TABLE IF EXISTS units;
DROP TABLE IF EXISTS store_sections;
