// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createCatalogAppliedRelease = `-- name: CreateCatalogAppliedRelease :one
INSERT INTO catalog_applied_releases (release_id, release_digest, manifest)
VALUES ($1, $2, $3)
RETURNING release_id, release_digest, manifest, applied_at
`

type CreateCatalogAppliedReleaseParams struct {
	ReleaseID     string          `db:"release_id" json:"release_id"`
	ReleaseDigest string          `db:"release_digest" json:"release_digest"`
	Manifest      json.RawMessage `db:"manifest" json:"manifest"`
}

func (q *Queries) CreateCatalogAppliedRelease(ctx context.Context, arg CreateCatalogAppliedReleaseParams) (CatalogAppliedRelease, error) {
	row := q.db.QueryRowContext(ctx, createCatalogAppliedRelease, arg.ReleaseID, arg.ReleaseDigest, arg.Manifest)
	var i CatalogAppliedRelease
	err := row.Scan(
		&i.ReleaseID,
		&i.ReleaseDigest,
		&i.Manifest,
		&i.AppliedAt,
	)
	return i, err
}

const createCatalogRecipe = `-- name: CreateCatalogRecipe :one
INSERT INTO catalog_recipes (
    key, name, status, recipe_document, source_identity, semantic_profile,
    source_url, source_attribution, document_digest, source_identity_digest,
    selected_recipe_digest, release_id, release_digest
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, key, name, status, recipe_document, source_identity, semantic_profile, source_url, source_attribution, document_digest, source_identity_digest, selected_recipe_digest, release_id, release_digest, published_at
`

type CreateCatalogRecipeParams struct {
	Key                  string          `db:"key" json:"key"`
	Name                 string          `db:"name" json:"name"`
	Status               string          `db:"status" json:"status"`
	RecipeDocument       json.RawMessage `db:"recipe_document" json:"recipe_document"`
	SourceIdentity       json.RawMessage `db:"source_identity" json:"source_identity"`
	SemanticProfile      json.RawMessage `db:"semantic_profile" json:"semantic_profile"`
	SourceUrl            sql.NullString  `db:"source_url" json:"source_url"`
	SourceAttribution    string          `db:"source_attribution" json:"source_attribution"`
	DocumentDigest       string          `db:"document_digest" json:"document_digest"`
	SourceIdentityDigest string          `db:"source_identity_digest" json:"source_identity_digest"`
	SelectedRecipeDigest string          `db:"selected_recipe_digest" json:"selected_recipe_digest"`
	ReleaseID            string          `db:"release_id" json:"release_id"`
	ReleaseDigest        string          `db:"release_digest" json:"release_digest"`
}

func (q *Queries) CreateCatalogRecipe(ctx context.Context, arg CreateCatalogRecipeParams) (CatalogRecipe, error) {
	row := q.db.QueryRowContext(ctx, createCatalogRecipe,
		arg.Key,
		arg.Name,
		arg.Status,
		arg.RecipeDocument,
		arg.SourceIdentity,
		arg.SemanticProfile,
		arg.SourceUrl,
		arg.SourceAttribution,
		arg.DocumentDigest,
		arg.SourceIdentityDigest,
		arg.SelectedRecipeDigest,
		arg.ReleaseID,
		arg.ReleaseDigest,
	)
	var i CatalogRecipe
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Status,
		&i.RecipeDocument,
		&i.SourceIdentity,
		&i.SemanticProfile,
		&i.SourceUrl,
		&i.SourceAttribution,
		&i.DocumentDigest,
		&i.SourceIdentityDigest,
		&i.SelectedRecipeDigest,
		&i.ReleaseID,
		&i.ReleaseDigest,
		&i.PublishedAt,
	)
	return i, err
}

const createHouseholdCatalogMembership = `-- name: CreateHouseholdCatalogMembership :one
INSERT INTO household_catalog_memberships (
    household_id, catalog_recipe_id, materialized_recipe_id, state, catalog_document_digest
) VALUES ($5, $1, $2, $3, $4)
RETURNING household_id, catalog_recipe_id, materialized_recipe_id, state, catalog_document_digest, created_at, updated_at
`

type CreateHouseholdCatalogMembershipParams struct {
	CatalogRecipeID       int64  `db:"catalog_recipe_id" json:"catalog_recipe_id"`
	MaterializedRecipeID  int64  `db:"materialized_recipe_id" json:"materialized_recipe_id"`
	State                 string `db:"state" json:"state"`
	CatalogDocumentDigest string `db:"catalog_document_digest" json:"catalog_document_digest"`
	HouseholdID           string `db:"household_id" json:"household_id"`
}

func (q *Queries) CreateHouseholdCatalogMembership(ctx context.Context, arg CreateHouseholdCatalogMembershipParams) (HouseholdCatalogMembership, error) {
	row := q.db.QueryRowContext(ctx, createHouseholdCatalogMembership,
		arg.CatalogRecipeID,
		arg.MaterializedRecipeID,
		arg.State,
		arg.CatalogDocumentDigest,
		arg.HouseholdID,
	)
	var i HouseholdCatalogMembership
	err := row.Scan(
		&i.HouseholdID,
		&i.CatalogRecipeID,
		&i.MaterializedRecipeID,
		&i.State,
		&i.CatalogDocumentDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCatalogAppliedRelease = `-- name: GetCatalogAppliedRelease :one
SELECT release_id, release_digest, manifest, applied_at FROM catalog_applied_releases WHERE release_id = $1
`

func (q *Queries) GetCatalogAppliedRelease(ctx context.Context, releaseID string) (CatalogAppliedRelease, error) {
	row := q.db.QueryRowContext(ctx, getCatalogAppliedRelease, releaseID)
	var i CatalogAppliedRelease
	err := row.Scan(
		&i.ReleaseID,
		&i.ReleaseDigest,
		&i.Manifest,
		&i.AppliedAt,
	)
	return i, err
}

const getCatalogRecipe = `-- name: GetCatalogRecipe :one
SELECT id, key, name, status, recipe_document, source_identity, semantic_profile, source_url, source_attribution, document_digest, source_identity_digest, selected_recipe_digest, release_id, release_digest, published_at FROM catalog_recipes WHERE id = $1
`

func (q *Queries) GetCatalogRecipe(ctx context.Context, id int64) (CatalogRecipe, error) {
	row := q.db.QueryRowContext(ctx, getCatalogRecipe, id)
	var i CatalogRecipe
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Status,
		&i.RecipeDocument,
		&i.SourceIdentity,
		&i.SemanticProfile,
		&i.SourceUrl,
		&i.SourceAttribution,
		&i.DocumentDigest,
		&i.SourceIdentityDigest,
		&i.SelectedRecipeDigest,
		&i.ReleaseID,
		&i.ReleaseDigest,
		&i.PublishedAt,
	)
	return i, err
}

const getCatalogRecipeByKey = `-- name: GetCatalogRecipeByKey :one
SELECT id, key, name, status, recipe_document, source_identity, semantic_profile, source_url, source_attribution, document_digest, source_identity_digest, selected_recipe_digest, release_id, release_digest, published_at FROM catalog_recipes WHERE key = $1
`

func (q *Queries) GetCatalogRecipeByKey(ctx context.Context, key string) (CatalogRecipe, error) {
	row := q.db.QueryRowContext(ctx, getCatalogRecipeByKey, key)
	var i CatalogRecipe
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Status,
		&i.RecipeDocument,
		&i.SourceIdentity,
		&i.SemanticProfile,
		&i.SourceUrl,
		&i.SourceAttribution,
		&i.DocumentDigest,
		&i.SourceIdentityDigest,
		&i.SelectedRecipeDigest,
		&i.ReleaseID,
		&i.ReleaseDigest,
		&i.PublishedAt,
	)
	return i, err
}

const getCatalogRecipeBySelectedRecipeDigest = `-- name: GetCatalogRecipeBySelectedRecipeDigest :one
SELECT id, key, name, status, recipe_document, source_identity, semantic_profile, source_url, source_attribution, document_digest, source_identity_digest, selected_recipe_digest, release_id, release_digest, published_at FROM catalog_recipes WHERE selected_recipe_digest = $1
`

func (q *Queries) GetCatalogRecipeBySelectedRecipeDigest(ctx context.Context, selectedRecipeDigest string) (CatalogRecipe, error) {
	row := q.db.QueryRowContext(ctx, getCatalogRecipeBySelectedRecipeDigest, selectedRecipeDigest)
	var i CatalogRecipe
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Status,
		&i.RecipeDocument,
		&i.SourceIdentity,
		&i.SemanticProfile,
		&i.SourceUrl,
		&i.SourceAttribution,
		&i.DocumentDigest,
		&i.SourceIdentityDigest,
		&i.SelectedRecipeDigest,
		&i.ReleaseID,
		&i.ReleaseDigest,
		&i.PublishedAt,
	)
	return i, err
}

const getCatalogRecipeBySourceIdentityDigest = `-- name: GetCatalogRecipeBySourceIdentityDigest :one
SELECT id, key, name, status, recipe_document, source_identity, semantic_profile, source_url, source_attribution, document_digest, source_identity_digest, selected_recipe_digest, release_id, release_digest, published_at FROM catalog_recipes WHERE source_identity_digest = $1
`

func (q *Queries) GetCatalogRecipeBySourceIdentityDigest(ctx context.Context, sourceIdentityDigest string) (CatalogRecipe, error) {
	row := q.db.QueryRowContext(ctx, getCatalogRecipeBySourceIdentityDigest, sourceIdentityDigest)
	var i CatalogRecipe
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Status,
		&i.RecipeDocument,
		&i.SourceIdentity,
		&i.SemanticProfile,
		&i.SourceUrl,
		&i.SourceAttribution,
		&i.DocumentDigest,
		&i.SourceIdentityDigest,
		&i.SelectedRecipeDigest,
		&i.ReleaseID,
		&i.ReleaseDigest,
		&i.PublishedAt,
	)
	return i, err
}

const getHouseholdCatalogMembership = `-- name: GetHouseholdCatalogMembership :one
SELECT household_id, catalog_recipe_id, materialized_recipe_id, state, catalog_document_digest, created_at, updated_at FROM household_catalog_memberships
WHERE household_id = $1 AND catalog_recipe_id = $2
`

type GetHouseholdCatalogMembershipParams struct {
	HouseholdID     string `db:"household_id" json:"household_id"`
	CatalogRecipeID int64  `db:"catalog_recipe_id" json:"catalog_recipe_id"`
}

func (q *Queries) GetHouseholdCatalogMembership(ctx context.Context, arg GetHouseholdCatalogMembershipParams) (HouseholdCatalogMembership, error) {
	row := q.db.QueryRowContext(ctx, getHouseholdCatalogMembership, arg.HouseholdID, arg.CatalogRecipeID)
	var i HouseholdCatalogMembership
	err := row.Scan(
		&i.HouseholdID,
		&i.CatalogRecipeID,
		&i.MaterializedRecipeID,
		&i.State,
		&i.CatalogDocumentDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVerifiedCatalogRecipes = `-- name: ListVerifiedCatalogRecipes :many
SELECT id, key, name, status, recipe_document, source_identity, semantic_profile, source_url, source_attribution, document_digest, source_identity_digest, selected_recipe_digest, release_id, release_digest, published_at FROM catalog_recipes WHERE status = 'verified' ORDER BY name
`

func (q *Queries) ListVerifiedCatalogRecipes(ctx context.Context) ([]CatalogRecipe, error) {
	rows, err := q.db.QueryContext(ctx, listVerifiedCatalogRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogRecipe{}
	for rows.Next() {
		var i CatalogRecipe
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Status,
			&i.RecipeDocument,
			&i.SourceIdentity,
			&i.SemanticProfile,
			&i.SourceUrl,
			&i.SourceAttribution,
			&i.DocumentDigest,
			&i.SourceIdentityDigest,
			&i.SelectedRecipeDigest,
			&i.ReleaseID,
			&i.ReleaseDigest,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteHouseholdCatalogMembership = `-- name: PromoteHouseholdCatalogMembership :one
UPDATE household_catalog_memberships
SET state = 'adopted', updated_at = clock_timestamp()
WHERE household_id = $1
  AND catalog_recipe_id = $2
  AND state = 'trial'
RETURNING household_id, catalog_recipe_id, materialized_recipe_id, state, catalog_document_digest, created_at, updated_at
`

type PromoteHouseholdCatalogMembershipParams struct {
	HouseholdID     string `db:"household_id" json:"household_id"`
	CatalogRecipeID int64  `db:"catalog_recipe_id" json:"catalog_recipe_id"`
}

func (q *Queries) PromoteHouseholdCatalogMembership(ctx context.Context, arg PromoteHouseholdCatalogMembershipParams) (HouseholdCatalogMembership, error) {
	row := q.db.QueryRowContext(ctx, promoteHouseholdCatalogMembership, arg.HouseholdID, arg.CatalogRecipeID)
	var i HouseholdCatalogMembership
	err := row.Scan(
		&i.HouseholdID,
		&i.CatalogRecipeID,
		&i.MaterializedRecipeID,
		&i.State,
		&i.CatalogDocumentDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
