// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: corpus.sql

package store

import (
	"context"
	"database/sql"
)

const approveReviewFlag = `-- name: ApproveReviewFlag :one
UPDATE recipe_review_flags SET approved = 1
WHERE id = ?
RETURNING id, recipe_id, field_path, kind, note, approved
`

func (q *Queries) ApproveReviewFlag(ctx context.Context, id int64) (RecipeReviewFlag, error) {
	row := q.db.QueryRowContext(ctx, approveReviewFlag, id)
	var i RecipeReviewFlag
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.FieldPath,
		&i.Kind,
		&i.Note,
		&i.Approved,
	)
	return i, err
}

const countUnapprovedReviewFlags = `-- name: CountUnapprovedReviewFlags :one
SELECT count(*) FROM recipe_review_flags WHERE recipe_id = ? AND approved = 0
`

func (q *Queries) CountUnapprovedReviewFlags(ctx context.Context, recipeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnapprovedReviewFlags, recipeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDraftRecipe = `-- name: CreateDraftRecipe :one
INSERT INTO recipes (
    key, name, image_url, yield_text,
    hands_on_min_minutes, hands_on_max_minutes,
    unattended_min_minutes, unattended_max_minutes
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, "key", name, status, image_url, yield_text, hands_on_min_minutes, hands_on_max_minutes, unattended_min_minutes, unattended_max_minutes, verified_at, created_at, updated_at
`

type CreateDraftRecipeParams struct {
	Key                  string         `db:"key" json:"key"`
	Name                 string         `db:"name" json:"name"`
	ImageUrl             sql.NullString `db:"image_url" json:"image_url"`
	YieldText            sql.NullString `db:"yield_text" json:"yield_text"`
	HandsOnMinMinutes    sql.NullInt64  `db:"hands_on_min_minutes" json:"hands_on_min_minutes"`
	HandsOnMaxMinutes    sql.NullInt64  `db:"hands_on_max_minutes" json:"hands_on_max_minutes"`
	UnattendedMinMinutes sql.NullInt64  `db:"unattended_min_minutes" json:"unattended_min_minutes"`
	UnattendedMaxMinutes sql.NullInt64  `db:"unattended_max_minutes" json:"unattended_max_minutes"`
}

func (q *Queries) CreateDraftRecipe(ctx context.Context, arg CreateDraftRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, createDraftRecipe,
		arg.Key,
		arg.Name,
		arg.ImageUrl,
		arg.YieldText,
		arg.HandsOnMinMinutes,
		arg.HandsOnMaxMinutes,
		arg.UnattendedMinMinutes,
		arg.UnattendedMaxMinutes,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Status,
		&i.ImageUrl,
		&i.YieldText,
		&i.HandsOnMinMinutes,
		&i.HandsOnMaxMinutes,
		&i.UnattendedMinMinutes,
		&i.UnattendedMaxMinutes,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroceryItem = `-- name: CreateGroceryItem :one
INSERT INTO grocery_items (key, name, store_section_id, shopping_mode)
VALUES (?, ?, ?, ?)
RETURNING id, "key", name, store_section_id, shopping_mode, created_at, updated_at
`

type CreateGroceryItemParams struct {
	Key            string `db:"key" json:"key"`
	Name           string `db:"name" json:"name"`
	StoreSectionID int64  `db:"store_section_id" json:"store_section_id"`
	ShoppingMode   string `db:"shopping_mode" json:"shopping_mode"`
}

func (q *Queries) CreateGroceryItem(ctx context.Context, arg CreateGroceryItemParams) (GroceryItem, error) {
	row := q.db.QueryRowContext(ctx, createGroceryItem,
		arg.Key,
		arg.Name,
		arg.StoreSectionID,
		arg.ShoppingMode,
	)
	var i GroceryItem
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.StoreSectionID,
		&i.ShoppingMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIngredientSection = `-- name: CreateIngredientSection :one
INSERT INTO recipe_ingredient_sections (recipe_id, name, position)
VALUES (?, ?, ?)
RETURNING id, recipe_id, name, position
`

type CreateIngredientSectionParams struct {
	RecipeID int64  `db:"recipe_id" json:"recipe_id"`
	Name     string `db:"name" json:"name"`
	Position int64  `db:"position" json:"position"`
}

func (q *Queries) CreateIngredientSection(ctx context.Context, arg CreateIngredientSectionParams) (RecipeIngredientSection, error) {
	row := q.db.QueryRowContext(ctx, createIngredientSection, arg.RecipeID, arg.Name, arg.Position)
	var i RecipeIngredientSection
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Name,
		&i.Position,
	)
	return i, err
}

const createInstructionSection = `-- name: CreateInstructionSection :one
INSERT INTO recipe_instruction_sections (recipe_id, name, position)
VALUES (?, ?, ?)
RETURNING id, recipe_id, name, position
`

type CreateInstructionSectionParams struct {
	RecipeID int64  `db:"recipe_id" json:"recipe_id"`
	Name     string `db:"name" json:"name"`
	Position int64  `db:"position" json:"position"`
}

func (q *Queries) CreateInstructionSection(ctx context.Context, arg CreateInstructionSectionParams) (RecipeInstructionSection, error) {
	row := q.db.QueryRowContext(ctx, createInstructionSection, arg.RecipeID, arg.Name, arg.Position)
	var i RecipeInstructionSection
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Name,
		&i.Position,
	)
	return i, err
}

const createRecipeIngredient = `-- name: CreateRecipeIngredient :one
INSERT INTO recipe_ingredients (
    section_id, grocery_item_id, position, source_text, quantity_kind,
    amount_min_numerator, amount_min_denominator,
    amount_max_numerator, amount_max_denominator,
    unit_id, package_type,
    package_size_numerator, package_size_denominator, package_size_unit_id,
    preparation, is_optional, display_note
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, section_id, grocery_item_id, position, source_text, quantity_kind, amount_min_numerator, amount_min_denominator, amount_max_numerator, amount_max_denominator, unit_id, package_type, package_size_numerator, package_size_denominator, package_size_unit_id, preparation, is_optional, display_note
`

type CreateRecipeIngredientParams struct {
	SectionID              int64          `db:"section_id" json:"section_id"`
	GroceryItemID          sql.NullInt64  `db:"grocery_item_id" json:"grocery_item_id"`
	Position               int64          `db:"position" json:"position"`
	SourceText             string         `db:"source_text" json:"source_text"`
	QuantityKind           string         `db:"quantity_kind" json:"quantity_kind"`
	AmountMinNumerator     sql.NullInt64  `db:"amount_min_numerator" json:"amount_min_numerator"`
	AmountMinDenominator   sql.NullInt64  `db:"amount_min_denominator" json:"amount_min_denominator"`
	AmountMaxNumerator     sql.NullInt64  `db:"amount_max_numerator" json:"amount_max_numerator"`
	AmountMaxDenominator   sql.NullInt64  `db:"amount_max_denominator" json:"amount_max_denominator"`
	UnitID                 sql.NullInt64  `db:"unit_id" json:"unit_id"`
	PackageType            sql.NullString `db:"package_type" json:"package_type"`
	PackageSizeNumerator   sql.NullInt64  `db:"package_size_numerator" json:"package_size_numerator"`
	PackageSizeDenominator sql.NullInt64  `db:"package_size_denominator" json:"package_size_denominator"`
	PackageSizeUnitID      sql.NullInt64  `db:"package_size_unit_id" json:"package_size_unit_id"`
	Preparation            sql.NullString `db:"preparation" json:"preparation"`
	IsOptional             int64          `db:"is_optional" json:"is_optional"`
	DisplayNote            sql.NullString `db:"display_note" json:"display_note"`
}

func (q *Queries) CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) (RecipeIngredient, error) {
	row := q.db.QueryRowContext(ctx, createRecipeIngredient,
		arg.SectionID,
		arg.GroceryItemID,
		arg.Position,
		arg.SourceText,
		arg.QuantityKind,
		arg.AmountMinNumerator,
		arg.AmountMinDenominator,
		arg.AmountMaxNumerator,
		arg.AmountMaxDenominator,
		arg.UnitID,
		arg.PackageType,
		arg.PackageSizeNumerator,
		arg.PackageSizeDenominator,
		arg.PackageSizeUnitID,
		arg.Preparation,
		arg.IsOptional,
		arg.DisplayNote,
	)
	var i RecipeIngredient
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.GroceryItemID,
		&i.Position,
		&i.SourceText,
		&i.QuantityKind,
		&i.AmountMinNumerator,
		&i.AmountMinDenominator,
		&i.AmountMaxNumerator,
		&i.AmountMaxDenominator,
		&i.UnitID,
		&i.PackageType,
		&i.PackageSizeNumerator,
		&i.PackageSizeDenominator,
		&i.PackageSizeUnitID,
		&i.Preparation,
		&i.IsOptional,
		&i.DisplayNote,
	)
	return i, err
}

const createRecipeSource = `-- name: CreateRecipeSource :one
INSERT INTO recipe_sources (
    recipe_id, relationship, attribution, url, checked_on, is_primary, position
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, recipe_id, relationship, attribution, url, checked_on, is_primary, position
`

type CreateRecipeSourceParams struct {
	RecipeID     int64          `db:"recipe_id" json:"recipe_id"`
	Relationship string         `db:"relationship" json:"relationship"`
	Attribution  string         `db:"attribution" json:"attribution"`
	Url          sql.NullString `db:"url" json:"url"`
	CheckedOn    sql.NullString `db:"checked_on" json:"checked_on"`
	IsPrimary    int64          `db:"is_primary" json:"is_primary"`
	Position     int64          `db:"position" json:"position"`
}

func (q *Queries) CreateRecipeSource(ctx context.Context, arg CreateRecipeSourceParams) (RecipeSource, error) {
	row := q.db.QueryRowContext(ctx, createRecipeSource,
		arg.RecipeID,
		arg.Relationship,
		arg.Attribution,
		arg.Url,
		arg.CheckedOn,
		arg.IsPrimary,
		arg.Position,
	)
	var i RecipeSource
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Relationship,
		&i.Attribution,
		&i.Url,
		&i.CheckedOn,
		&i.IsPrimary,
		&i.Position,
	)
	return i, err
}

const createRecipeStep = `-- name: CreateRecipeStep :one
INSERT INTO recipe_steps (section_id, position, instruction)
VALUES (?, ?, ?)
RETURNING id, section_id, position, instruction
`

type CreateRecipeStepParams struct {
	SectionID   int64  `db:"section_id" json:"section_id"`
	Position    int64  `db:"position" json:"position"`
	Instruction string `db:"instruction" json:"instruction"`
}

func (q *Queries) CreateRecipeStep(ctx context.Context, arg CreateRecipeStepParams) (RecipeStep, error) {
	row := q.db.QueryRowContext(ctx, createRecipeStep, arg.SectionID, arg.Position, arg.Instruction)
	var i RecipeStep
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Position,
		&i.Instruction,
	)
	return i, err
}

const createReviewFlag = `-- name: CreateReviewFlag :one
INSERT INTO recipe_review_flags (recipe_id, field_path, kind, note)
VALUES (?, ?, ?, ?)
RETURNING id, recipe_id, field_path, kind, note, approved
`

type CreateReviewFlagParams struct {
	RecipeID  int64  `db:"recipe_id" json:"recipe_id"`
	FieldPath string `db:"field_path" json:"field_path"`
	Kind      string `db:"kind" json:"kind"`
	Note      string `db:"note" json:"note"`
}

func (q *Queries) CreateReviewFlag(ctx context.Context, arg CreateReviewFlagParams) (RecipeReviewFlag, error) {
	row := q.db.QueryRowContext(ctx, createReviewFlag,
		arg.RecipeID,
		arg.FieldPath,
		arg.Kind,
		arg.Note,
	)
	var i RecipeReviewFlag
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.FieldPath,
		&i.Kind,
		&i.Note,
		&i.Approved,
	)
	return i, err
}

const createStoreSection = `-- name: CreateStoreSection :one
INSERT INTO store_sections (key, name) VALUES (?, ?)
RETURNING id, "key", name
`

type CreateStoreSectionParams struct {
	Key  string `db:"key" json:"key"`
	Name string `db:"name" json:"name"`
}

func (q *Queries) CreateStoreSection(ctx context.Context, arg CreateStoreSectionParams) (StoreSection, error) {
	row := q.db.QueryRowContext(ctx, createStoreSection, arg.Key, arg.Name)
	var i StoreSection
	err := row.Scan(&i.ID, &i.Key, &i.Name)
	return i, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (
    key, name, symbol, dimension, to_base_numerator, to_base_denominator
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, "key", name, symbol, dimension, to_base_numerator, to_base_denominator
`

type CreateUnitParams struct {
	Key               string `db:"key" json:"key"`
	Name              string `db:"name" json:"name"`
	Symbol            string `db:"symbol" json:"symbol"`
	Dimension         string `db:"dimension" json:"dimension"`
	ToBaseNumerator   int64  `db:"to_base_numerator" json:"to_base_numerator"`
	ToBaseDenominator int64  `db:"to_base_denominator" json:"to_base_denominator"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, createUnit,
		arg.Key,
		arg.Name,
		arg.Symbol,
		arg.Dimension,
		arg.ToBaseNumerator,
		arg.ToBaseDenominator,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Symbol,
		&i.Dimension,
		&i.ToBaseNumerator,
		&i.ToBaseDenominator,
	)
	return i, err
}

const getGroceryItemByKey = `-- name: GetGroceryItemByKey :one
SELECT id, "key", name, store_section_id, shopping_mode, created_at, updated_at FROM grocery_items WHERE key = ?
`

func (q *Queries) GetGroceryItemByKey(ctx context.Context, key string) (GroceryItem, error) {
	row := q.db.QueryRowContext(ctx, getGroceryItemByKey, key)
	var i GroceryItem
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.StoreSectionID,
		&i.ShoppingMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, "key", name, status, image_url, yield_text, hands_on_min_minutes, hands_on_max_minutes, unattended_min_minutes, unattended_max_minutes, verified_at, created_at, updated_at FROM recipes WHERE id = ?
`

func (q *Queries) GetRecipe(ctx context.Context, id int64) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Status,
		&i.ImageUrl,
		&i.YieldText,
		&i.HandsOnMinMinutes,
		&i.HandsOnMaxMinutes,
		&i.UnattendedMinMinutes,
		&i.UnattendedMaxMinutes,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeByKey = `-- name: GetRecipeByKey :one
SELECT id, "key", name, status, image_url, yield_text, hands_on_min_minutes, hands_on_max_minutes, unattended_min_minutes, unattended_max_minutes, verified_at, created_at, updated_at FROM recipes WHERE key = ?
`

func (q *Queries) GetRecipeByKey(ctx context.Context, key string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipeByKey, key)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Status,
		&i.ImageUrl,
		&i.YieldText,
		&i.HandsOnMinMinutes,
		&i.HandsOnMaxMinutes,
		&i.UnattendedMinMinutes,
		&i.UnattendedMaxMinutes,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroceryItems = `-- name: ListGroceryItems :many
SELECT gi.id, gi."key", gi.name, gi.store_section_id, gi.shopping_mode, gi.created_at, gi.updated_at, ss.name AS store_section_name
FROM grocery_items gi
JOIN store_sections ss ON ss.id = gi.store_section_id
ORDER BY gi.name
`

type ListGroceryItemsRow struct {
	ID               int64  `db:"id" json:"id"`
	Key              string `db:"key" json:"key"`
	Name             string `db:"name" json:"name"`
	StoreSectionID   int64  `db:"store_section_id" json:"store_section_id"`
	ShoppingMode     string `db:"shopping_mode" json:"shopping_mode"`
	CreatedAt        string `db:"created_at" json:"created_at"`
	UpdatedAt        string `db:"updated_at" json:"updated_at"`
	StoreSectionName string `db:"store_section_name" json:"store_section_name"`
}

func (q *Queries) ListGroceryItems(ctx context.Context) ([]ListGroceryItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroceryItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroceryItemsRow{}
	for rows.Next() {
		var i ListGroceryItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.StoreSectionID,
			&i.ShoppingMode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StoreSectionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientSections = `-- name: ListIngredientSections :many
SELECT id, recipe_id, name, position FROM recipe_ingredient_sections WHERE recipe_id = ? ORDER BY position
`

func (q *Queries) ListIngredientSections(ctx context.Context, recipeID int64) ([]RecipeIngredientSection, error) {
	rows, err := q.db.QueryContext(ctx, listIngredientSections, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeIngredientSection{}
	for rows.Next() {
		var i RecipeIngredientSection
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Name,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstructionSections = `-- name: ListInstructionSections :many
SELECT id, recipe_id, name, position FROM recipe_instruction_sections WHERE recipe_id = ? ORDER BY position
`

func (q *Queries) ListInstructionSections(ctx context.Context, recipeID int64) ([]RecipeInstructionSection, error) {
	rows, err := q.db.QueryContext(ctx, listInstructionSections, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeInstructionSection{}
	for rows.Next() {
		var i RecipeInstructionSection
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Name,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeIngredients = `-- name: ListRecipeIngredients :many
SELECT
    ri.id, ri.section_id, ri.grocery_item_id, ri.position, ri.source_text, ri.quantity_kind, ri.amount_min_numerator, ri.amount_min_denominator, ri.amount_max_numerator, ri.amount_max_denominator, ri.unit_id, ri.package_type, ri.package_size_numerator, ri.package_size_denominator, ri.package_size_unit_id, ri.preparation, ri.is_optional, ri.display_note,
    ris.recipe_id,
    ris.name AS section_name,
    ris.position AS section_position,
    gi.key AS grocery_item_key,
    gi.name AS grocery_item_name,
    gi.shopping_mode,
    ss.name AS store_section_name,
    u.key AS unit_key,
    psu.key AS package_size_unit_key
FROM recipe_ingredients ri
JOIN recipe_ingredient_sections ris ON ris.id = ri.section_id
LEFT JOIN grocery_items gi ON gi.id = ri.grocery_item_id
LEFT JOIN store_sections ss ON ss.id = gi.store_section_id
LEFT JOIN units u ON u.id = ri.unit_id
LEFT JOIN units psu ON psu.id = ri.package_size_unit_id
WHERE ris.recipe_id = ?
ORDER BY ris.position, ri.position
`

type ListRecipeIngredientsRow struct {
	ID                     int64          `db:"id" json:"id"`
	SectionID              int64          `db:"section_id" json:"section_id"`
	GroceryItemID          sql.NullInt64  `db:"grocery_item_id" json:"grocery_item_id"`
	Position               int64          `db:"position" json:"position"`
	SourceText             string         `db:"source_text" json:"source_text"`
	QuantityKind           string         `db:"quantity_kind" json:"quantity_kind"`
	AmountMinNumerator     sql.NullInt64  `db:"amount_min_numerator" json:"amount_min_numerator"`
	AmountMinDenominator   sql.NullInt64  `db:"amount_min_denominator" json:"amount_min_denominator"`
	AmountMaxNumerator     sql.NullInt64  `db:"amount_max_numerator" json:"amount_max_numerator"`
	AmountMaxDenominator   sql.NullInt64  `db:"amount_max_denominator" json:"amount_max_denominator"`
	UnitID                 sql.NullInt64  `db:"unit_id" json:"unit_id"`
	PackageType            sql.NullString `db:"package_type" json:"package_type"`
	PackageSizeNumerator   sql.NullInt64  `db:"package_size_numerator" json:"package_size_numerator"`
	PackageSizeDenominator sql.NullInt64  `db:"package_size_denominator" json:"package_size_denominator"`
	PackageSizeUnitID      sql.NullInt64  `db:"package_size_unit_id" json:"package_size_unit_id"`
	Preparation            sql.NullString `db:"preparation" json:"preparation"`
	IsOptional             int64          `db:"is_optional" json:"is_optional"`
	DisplayNote            sql.NullString `db:"display_note" json:"display_note"`
	RecipeID               int64          `db:"recipe_id" json:"recipe_id"`
	SectionName            string         `db:"section_name" json:"section_name"`
	SectionPosition        int64          `db:"section_position" json:"section_position"`
	GroceryItemKey         sql.NullString `db:"grocery_item_key" json:"grocery_item_key"`
	GroceryItemName        sql.NullString `db:"grocery_item_name" json:"grocery_item_name"`
	ShoppingMode           sql.NullString `db:"shopping_mode" json:"shopping_mode"`
	StoreSectionName       sql.NullString `db:"store_section_name" json:"store_section_name"`
	UnitKey                sql.NullString `db:"unit_key" json:"unit_key"`
	PackageSizeUnitKey     sql.NullString `db:"package_size_unit_key" json:"package_size_unit_key"`
}

func (q *Queries) ListRecipeIngredients(ctx context.Context, recipeID int64) ([]ListRecipeIngredientsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeIngredients, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipeIngredientsRow{}
	for rows.Next() {
		var i ListRecipeIngredientsRow
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.GroceryItemID,
			&i.Position,
			&i.SourceText,
			&i.QuantityKind,
			&i.AmountMinNumerator,
			&i.AmountMinDenominator,
			&i.AmountMaxNumerator,
			&i.AmountMaxDenominator,
			&i.UnitID,
			&i.PackageType,
			&i.PackageSizeNumerator,
			&i.PackageSizeDenominator,
			&i.PackageSizeUnitID,
			&i.Preparation,
			&i.IsOptional,
			&i.DisplayNote,
			&i.RecipeID,
			&i.SectionName,
			&i.SectionPosition,
			&i.GroceryItemKey,
			&i.GroceryItemName,
			&i.ShoppingMode,
			&i.StoreSectionName,
			&i.UnitKey,
			&i.PackageSizeUnitKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeReviewFlags = `-- name: ListRecipeReviewFlags :many
SELECT id, recipe_id, field_path, kind, note, approved FROM recipe_review_flags WHERE recipe_id = ? ORDER BY field_path, kind
`

func (q *Queries) ListRecipeReviewFlags(ctx context.Context, recipeID int64) ([]RecipeReviewFlag, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeReviewFlags, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeReviewFlag{}
	for rows.Next() {
		var i RecipeReviewFlag
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.FieldPath,
			&i.Kind,
			&i.Note,
			&i.Approved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeSources = `-- name: ListRecipeSources :many
SELECT id, recipe_id, relationship, attribution, url, checked_on, is_primary, position FROM recipe_sources WHERE recipe_id = ? ORDER BY position
`

func (q *Queries) ListRecipeSources(ctx context.Context, recipeID int64) ([]RecipeSource, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeSources, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeSource{}
	for rows.Next() {
		var i RecipeSource
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Relationship,
			&i.Attribution,
			&i.Url,
			&i.CheckedOn,
			&i.IsPrimary,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeSteps = `-- name: ListRecipeSteps :many
SELECT rs.id, rs.section_id, rs.position, rs.instruction, ris.recipe_id, ris.name AS section_name, ris.position AS section_position
FROM recipe_steps rs
JOIN recipe_instruction_sections ris ON ris.id = rs.section_id
WHERE ris.recipe_id = ?
ORDER BY ris.position, rs.position
`

type ListRecipeStepsRow struct {
	ID              int64  `db:"id" json:"id"`
	SectionID       int64  `db:"section_id" json:"section_id"`
	Position        int64  `db:"position" json:"position"`
	Instruction     string `db:"instruction" json:"instruction"`
	RecipeID        int64  `db:"recipe_id" json:"recipe_id"`
	SectionName     string `db:"section_name" json:"section_name"`
	SectionPosition int64  `db:"section_position" json:"section_position"`
}

func (q *Queries) ListRecipeSteps(ctx context.Context, recipeID int64) ([]ListRecipeStepsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeSteps, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipeStepsRow{}
	for rows.Next() {
		var i ListRecipeStepsRow
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Position,
			&i.Instruction,
			&i.RecipeID,
			&i.SectionName,
			&i.SectionPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreSections = `-- name: ListStoreSections :many
SELECT id, "key", name FROM store_sections ORDER BY name
`

func (q *Queries) ListStoreSections(ctx context.Context) ([]StoreSection, error) {
	rows, err := q.db.QueryContext(ctx, listStoreSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoreSection{}
	for rows.Next() {
		var i StoreSection
		if err := rows.Scan(&i.ID, &i.Key, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT id, "key", name, symbol, dimension, to_base_numerator, to_base_denominator FROM units ORDER BY dimension, name
`

func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.QueryContext(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Symbol,
			&i.Dimension,
			&i.ToBaseNumerator,
			&i.ToBaseDenominator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedRecipes = `-- name: ListVerifiedRecipes :many
SELECT id, "key", name, status, image_url, yield_text, hands_on_min_minutes, hands_on_max_minutes, unattended_min_minutes, unattended_max_minutes, verified_at, created_at, updated_at FROM recipes WHERE status = 'verified' ORDER BY name
`

func (q *Queries) ListVerifiedRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listVerifiedRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Status,
			&i.ImageUrl,
			&i.YieldText,
			&i.HandsOnMinMinutes,
			&i.HandsOnMaxMinutes,
			&i.UnattendedMinMinutes,
			&i.UnattendedMaxMinutes,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecipeReviewable = `-- name: MarkRecipeReviewable :one
UPDATE recipes
SET status = 'reviewable', verified_at = NULL,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND status = 'draft'
RETURNING id, "key", name, status, image_url, yield_text, hands_on_min_minutes, hands_on_max_minutes, unattended_min_minutes, unattended_max_minutes, verified_at, created_at, updated_at
`

func (q *Queries) MarkRecipeReviewable(ctx context.Context, id int64) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, markRecipeReviewable, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Status,
		&i.ImageUrl,
		&i.YieldText,
		&i.HandsOnMinMinutes,
		&i.HandsOnMaxMinutes,
		&i.UnattendedMinMinutes,
		&i.UnattendedMaxMinutes,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const returnRecipeToDraft = `-- name: ReturnRecipeToDraft :one
UPDATE recipes
SET status = 'draft', verified_at = NULL,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND status IN ('reviewable', 'verified')
RETURNING id, "key", name, status, image_url, yield_text, hands_on_min_minutes, hands_on_max_minutes, unattended_min_minutes, unattended_max_minutes, verified_at, created_at, updated_at
`

func (q *Queries) ReturnRecipeToDraft(ctx context.Context, id int64) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, returnRecipeToDraft, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Status,
		&i.ImageUrl,
		&i.YieldText,
		&i.HandsOnMinMinutes,
		&i.HandsOnMaxMinutes,
		&i.UnattendedMinMinutes,
		&i.UnattendedMaxMinutes,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyRecipe = `-- name: VerifyRecipe :one
UPDATE recipes
SET status = 'verified', verified_at = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND status = 'reviewable'
RETURNING id, "key", name, status, image_url, yield_text, hands_on_min_minutes, hands_on_max_minutes, unattended_min_minutes, unattended_max_minutes, verified_at, created_at, updated_at
`

type VerifyRecipeParams struct {
	VerifiedAt sql.NullString `db:"verified_at" json:"verified_at"`
	ID         int64          `db:"id" json:"id"`
}

func (q *Queries) VerifyRecipe(ctx context.Context, arg VerifyRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, verifyRecipe, arg.VerifiedAt, arg.ID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Status,
		&i.ImageUrl,
		&i.YieldText,
		&i.HandsOnMinMinutes,
		&i.HandsOnMaxMinutes,
		&i.UnattendedMinMinutes,
		&i.UnattendedMaxMinutes,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
