// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"
)

type AppUser struct {
	ID           string         `db:"id" json:"id"`
	PrimaryEmail string         `db:"primary_email" json:"primary_email"`
	DisplayName  string         `db:"display_name" json:"display_name"`
	AvatarUrl    sql.NullString `db:"avatar_url" json:"avatar_url"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
	LastSeenAt   time.Time      `db:"last_seen_at" json:"last_seen_at"`
	DisabledAt   sql.NullTime   `db:"disabled_at" json:"disabled_at"`
}

type AuthSession struct {
	ID                string         `db:"id" json:"id"`
	UserID            string         `db:"user_id" json:"user_id"`
	TokenDigest       []byte         `db:"token_digest" json:"token_digest"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	LastSeenAt        time.Time      `db:"last_seen_at" json:"last_seen_at"`
	IdleExpiresAt     time.Time      `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt time.Time      `db:"absolute_expires_at" json:"absolute_expires_at"`
	RevokedAt         sql.NullTime   `db:"revoked_at" json:"revoked_at"`
	ClientMetadata    sql.NullString `db:"client_metadata" json:"client_metadata"`
}

type GroceryItem struct {
	ID             int64  `db:"id" json:"id"`
	Key            string `db:"key" json:"key"`
	Name           string `db:"name" json:"name"`
	StoreSectionID int64  `db:"store_section_id" json:"store_section_id"`
	ShoppingMode   string `db:"shopping_mode" json:"shopping_mode"`
	CreatedAt      string `db:"created_at" json:"created_at"`
	UpdatedAt      string `db:"updated_at" json:"updated_at"`
	HouseholdID    string `db:"household_id" json:"household_id"`
}

type Household struct {
	ID        string    `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type HouseholdMembership struct {
	HouseholdID string    `db:"household_id" json:"household_id"`
	UserID      string    `db:"user_id" json:"user_id"`
	Role        string    `db:"role" json:"role"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

type Recipe struct {
	ID                   int64          `db:"id" json:"id"`
	Key                  string         `db:"key" json:"key"`
	Name                 string         `db:"name" json:"name"`
	Status               string         `db:"status" json:"status"`
	ImageUrl             sql.NullString `db:"image_url" json:"image_url"`
	YieldText            sql.NullString `db:"yield_text" json:"yield_text"`
	HandsOnMinMinutes    sql.NullInt64  `db:"hands_on_min_minutes" json:"hands_on_min_minutes"`
	HandsOnMaxMinutes    sql.NullInt64  `db:"hands_on_max_minutes" json:"hands_on_max_minutes"`
	UnattendedMinMinutes sql.NullInt64  `db:"unattended_min_minutes" json:"unattended_min_minutes"`
	UnattendedMaxMinutes sql.NullInt64  `db:"unattended_max_minutes" json:"unattended_max_minutes"`
	VerifiedAt           sql.NullString `db:"verified_at" json:"verified_at"`
	CreatedAt            string         `db:"created_at" json:"created_at"`
	UpdatedAt            string         `db:"updated_at" json:"updated_at"`
	HouseholdID          string         `db:"household_id" json:"household_id"`
}

type RecipeIngredient struct {
	ID                     int64          `db:"id" json:"id"`
	SectionID              int64          `db:"section_id" json:"section_id"`
	GroceryItemID          sql.NullInt64  `db:"grocery_item_id" json:"grocery_item_id"`
	Position               int64          `db:"position" json:"position"`
	SourceText             string         `db:"source_text" json:"source_text"`
	QuantityKind           string         `db:"quantity_kind" json:"quantity_kind"`
	AmountMinNumerator     sql.NullInt64  `db:"amount_min_numerator" json:"amount_min_numerator"`
	AmountMinDenominator   sql.NullInt64  `db:"amount_min_denominator" json:"amount_min_denominator"`
	AmountMaxNumerator     sql.NullInt64  `db:"amount_max_numerator" json:"amount_max_numerator"`
	AmountMaxDenominator   sql.NullInt64  `db:"amount_max_denominator" json:"amount_max_denominator"`
	UnitID                 sql.NullInt64  `db:"unit_id" json:"unit_id"`
	PackageType            sql.NullString `db:"package_type" json:"package_type"`
	PackageSizeNumerator   sql.NullInt64  `db:"package_size_numerator" json:"package_size_numerator"`
	PackageSizeDenominator sql.NullInt64  `db:"package_size_denominator" json:"package_size_denominator"`
	PackageSizeUnitID      sql.NullInt64  `db:"package_size_unit_id" json:"package_size_unit_id"`
	Preparation            sql.NullString `db:"preparation" json:"preparation"`
	IsOptional             int64          `db:"is_optional" json:"is_optional"`
	IncludeOnGroceryList   int64          `db:"include_on_grocery_list" json:"include_on_grocery_list"`
	DisplayNote            sql.NullString `db:"display_note" json:"display_note"`
}

type RecipeIngredientSection struct {
	ID       int64  `db:"id" json:"id"`
	RecipeID int64  `db:"recipe_id" json:"recipe_id"`
	Name     string `db:"name" json:"name"`
	Position int64  `db:"position" json:"position"`
}

type RecipeInstructionSection struct {
	ID       int64  `db:"id" json:"id"`
	RecipeID int64  `db:"recipe_id" json:"recipe_id"`
	Name     string `db:"name" json:"name"`
	Position int64  `db:"position" json:"position"`
}

type RecipeReviewFlag struct {
	ID        int64  `db:"id" json:"id"`
	RecipeID  int64  `db:"recipe_id" json:"recipe_id"`
	FieldPath string `db:"field_path" json:"field_path"`
	Kind      string `db:"kind" json:"kind"`
	Note      string `db:"note" json:"note"`
	Approved  int64  `db:"approved" json:"approved"`
}

type RecipeSource struct {
	ID           int64          `db:"id" json:"id"`
	RecipeID     int64          `db:"recipe_id" json:"recipe_id"`
	Relationship string         `db:"relationship" json:"relationship"`
	Attribution  string         `db:"attribution" json:"attribution"`
	Url          sql.NullString `db:"url" json:"url"`
	CheckedOn    sql.NullString `db:"checked_on" json:"checked_on"`
	IsPrimary    int64          `db:"is_primary" json:"is_primary"`
	Position     int64          `db:"position" json:"position"`
}

type RecipeStep struct {
	ID          int64  `db:"id" json:"id"`
	SectionID   int64  `db:"section_id" json:"section_id"`
	Position    int64  `db:"position" json:"position"`
	Instruction string `db:"instruction" json:"instruction"`
}

type ShoppingLine struct {
	ID                     int64          `db:"id" json:"id"`
	ShoppingListID         int64          `db:"shopping_list_id" json:"shopping_list_id"`
	GroceryItemID          sql.NullInt64  `db:"grocery_item_id" json:"grocery_item_id"`
	StoreSectionID         int64          `db:"store_section_id" json:"store_section_id"`
	AggregationKey         sql.NullString `db:"aggregation_key" json:"aggregation_key"`
	Origin                 string         `db:"origin" json:"origin"`
	DisplayName            string         `db:"display_name" json:"display_name"`
	QuantityKind           string         `db:"quantity_kind" json:"quantity_kind"`
	AmountMinNumerator     sql.NullInt64  `db:"amount_min_numerator" json:"amount_min_numerator"`
	AmountMinDenominator   sql.NullInt64  `db:"amount_min_denominator" json:"amount_min_denominator"`
	AmountMaxNumerator     sql.NullInt64  `db:"amount_max_numerator" json:"amount_max_numerator"`
	AmountMaxDenominator   sql.NullInt64  `db:"amount_max_denominator" json:"amount_max_denominator"`
	UnitID                 sql.NullInt64  `db:"unit_id" json:"unit_id"`
	PackageType            sql.NullString `db:"package_type" json:"package_type"`
	PackageSizeNumerator   sql.NullInt64  `db:"package_size_numerator" json:"package_size_numerator"`
	PackageSizeDenominator sql.NullInt64  `db:"package_size_denominator" json:"package_size_denominator"`
	PackageSizeUnitID      sql.NullInt64  `db:"package_size_unit_id" json:"package_size_unit_id"`
	IsOptional             int64          `db:"is_optional" json:"is_optional"`
	IsRemoved              int64          `db:"is_removed" json:"is_removed"`
	IsCompleted            int64          `db:"is_completed" json:"is_completed"`
	DisplayPosition        int64          `db:"display_position" json:"display_position"`
	OverrideText           sql.NullString `db:"override_text" json:"override_text"`
	CreatedAt              string         `db:"created_at" json:"created_at"`
	UpdatedAt              string         `db:"updated_at" json:"updated_at"`
	HouseholdID            string         `db:"household_id" json:"household_id"`
}

type ShoppingLineContribution struct {
	ID                     int64          `db:"id" json:"id"`
	ShoppingLineID         int64          `db:"shopping_line_id" json:"shopping_line_id"`
	WeekRecipeID           int64          `db:"week_recipe_id" json:"week_recipe_id"`
	RecipeIngredientID     int64          `db:"recipe_ingredient_id" json:"recipe_ingredient_id"`
	QuantityKind           string         `db:"quantity_kind" json:"quantity_kind"`
	AmountMinNumerator     sql.NullInt64  `db:"amount_min_numerator" json:"amount_min_numerator"`
	AmountMinDenominator   sql.NullInt64  `db:"amount_min_denominator" json:"amount_min_denominator"`
	AmountMaxNumerator     sql.NullInt64  `db:"amount_max_numerator" json:"amount_max_numerator"`
	AmountMaxDenominator   sql.NullInt64  `db:"amount_max_denominator" json:"amount_max_denominator"`
	UnitID                 sql.NullInt64  `db:"unit_id" json:"unit_id"`
	PackageType            sql.NullString `db:"package_type" json:"package_type"`
	PackageSizeNumerator   sql.NullInt64  `db:"package_size_numerator" json:"package_size_numerator"`
	PackageSizeDenominator sql.NullInt64  `db:"package_size_denominator" json:"package_size_denominator"`
	PackageSizeUnitID      sql.NullInt64  `db:"package_size_unit_id" json:"package_size_unit_id"`
	IsOptional             int64          `db:"is_optional" json:"is_optional"`
	HouseholdID            string         `db:"household_id" json:"household_id"`
}

type ShoppingList struct {
	ID          int64  `db:"id" json:"id"`
	WeekID      int64  `db:"week_id" json:"week_id"`
	CreatedAt   string `db:"created_at" json:"created_at"`
	UpdatedAt   string `db:"updated_at" json:"updated_at"`
	HouseholdID string `db:"household_id" json:"household_id"`
}

type StoreSection struct {
	ID          int64  `db:"id" json:"id"`
	Key         string `db:"key" json:"key"`
	Name        string `db:"name" json:"name"`
	HouseholdID string `db:"household_id" json:"household_id"`
}

type Unit struct {
	ID                int64  `db:"id" json:"id"`
	Key               string `db:"key" json:"key"`
	Name              string `db:"name" json:"name"`
	Symbol            string `db:"symbol" json:"symbol"`
	Dimension         string `db:"dimension" json:"dimension"`
	ToBaseNumerator   int64  `db:"to_base_numerator" json:"to_base_numerator"`
	ToBaseDenominator int64  `db:"to_base_denominator" json:"to_base_denominator"`
}

type UserIdentity struct {
	ID                    string    `db:"id" json:"id"`
	UserID                string    `db:"user_id" json:"user_id"`
	Provider              string    `db:"provider" json:"provider"`
	Issuer                string    `db:"issuer" json:"issuer"`
	Subject               string    `db:"subject" json:"subject"`
	ProviderEmail         string    `db:"provider_email" json:"provider_email"`
	ProviderEmailVerified bool      `db:"provider_email_verified" json:"provider_email_verified"`
	CreatedAt             time.Time `db:"created_at" json:"created_at"`
	LastSeenAt            time.Time `db:"last_seen_at" json:"last_seen_at"`
}

type Week struct {
	ID          int64  `db:"id" json:"id"`
	StartsOn    string `db:"starts_on" json:"starts_on"`
	CreatedAt   string `db:"created_at" json:"created_at"`
	UpdatedAt   string `db:"updated_at" json:"updated_at"`
	HouseholdID string `db:"household_id" json:"household_id"`
}

type WeekRecipe struct {
	ID          int64  `db:"id" json:"id"`
	WeekID      int64  `db:"week_id" json:"week_id"`
	RecipeID    int64  `db:"recipe_id" json:"recipe_id"`
	Position    int64  `db:"position" json:"position"`
	CreatedAt   string `db:"created_at" json:"created_at"`
	HouseholdID string `db:"household_id" json:"household_id"`
}
