// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	ApproveReviewFlag(ctx context.Context, id int64) (RecipeReviewFlag, error)
	CountUnapprovedReviewFlags(ctx context.Context, recipeID int64) (int64, error)
	CreateDraftRecipe(ctx context.Context, arg CreateDraftRecipeParams) (Recipe, error)
	CreateGroceryItem(ctx context.Context, arg CreateGroceryItemParams) (GroceryItem, error)
	CreateIngredientSection(ctx context.Context, arg CreateIngredientSectionParams) (RecipeIngredientSection, error)
	CreateInstructionSection(ctx context.Context, arg CreateInstructionSectionParams) (RecipeInstructionSection, error)
	CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) (RecipeIngredient, error)
	CreateRecipeSource(ctx context.Context, arg CreateRecipeSourceParams) (RecipeSource, error)
	CreateRecipeStep(ctx context.Context, arg CreateRecipeStepParams) (RecipeStep, error)
	CreateReviewFlag(ctx context.Context, arg CreateReviewFlagParams) (RecipeReviewFlag, error)
	CreateStoreSection(ctx context.Context, arg CreateStoreSectionParams) (StoreSection, error)
	CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error)
	GetGroceryItemByKey(ctx context.Context, key string) (GroceryItem, error)
	GetRecipe(ctx context.Context, id int64) (Recipe, error)
	GetRecipeByKey(ctx context.Context, key string) (Recipe, error)
	GetStoreSectionByKey(ctx context.Context, key string) (StoreSection, error)
	GetUnitByKey(ctx context.Context, key string) (Unit, error)
	ListGroceryItems(ctx context.Context) ([]ListGroceryItemsRow, error)
	ListIngredientSections(ctx context.Context, recipeID int64) ([]RecipeIngredientSection, error)
	ListInstructionSections(ctx context.Context, recipeID int64) ([]RecipeInstructionSection, error)
	ListRecipeIngredients(ctx context.Context, recipeID int64) ([]ListRecipeIngredientsRow, error)
	ListRecipeReviewFlags(ctx context.Context, recipeID int64) ([]RecipeReviewFlag, error)
	ListRecipeSources(ctx context.Context, recipeID int64) ([]RecipeSource, error)
	ListRecipeSteps(ctx context.Context, recipeID int64) ([]ListRecipeStepsRow, error)
	ListStoreSections(ctx context.Context) ([]StoreSection, error)
	ListUnits(ctx context.Context) ([]Unit, error)
	ListVerifiedRecipes(ctx context.Context) ([]Recipe, error)
	MarkRecipeReviewable(ctx context.Context, id int64) (Recipe, error)
	ReturnRecipeToDraft(ctx context.Context, id int64) (Recipe, error)
	VerifyRecipe(ctx context.Context, arg VerifyRecipeParams) (Recipe, error)
}

var _ Querier = (*Queries)(nil)
