// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	ApproveReviewFlag(ctx context.Context, id int64) (RecipeReviewFlag, error)
	CountUnapprovedReviewFlags(ctx context.Context, recipeID int64) (int64, error)
	CreateDraftRecipe(ctx context.Context, arg CreateDraftRecipeParams) (Recipe, error)
	CreateGeneratedShoppingLine(ctx context.Context, arg CreateGeneratedShoppingLineParams) (ShoppingLine, error)
	CreateGroceryItem(ctx context.Context, arg CreateGroceryItemParams) (GroceryItem, error)
	CreateIngredientSection(ctx context.Context, arg CreateIngredientSectionParams) (RecipeIngredientSection, error)
	CreateInstructionSection(ctx context.Context, arg CreateInstructionSectionParams) (RecipeInstructionSection, error)
	CreateManualShoppingLine(ctx context.Context, arg CreateManualShoppingLineParams) (ShoppingLine, error)
	CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) (RecipeIngredient, error)
	CreateRecipeSource(ctx context.Context, arg CreateRecipeSourceParams) (RecipeSource, error)
	CreateRecipeStep(ctx context.Context, arg CreateRecipeStepParams) (RecipeStep, error)
	CreateReviewFlag(ctx context.Context, arg CreateReviewFlagParams) (RecipeReviewFlag, error)
	CreateShoppingLineContribution(ctx context.Context, arg CreateShoppingLineContributionParams) (ShoppingLineContribution, error)
	CreateShoppingList(ctx context.Context, weekID int64) (ShoppingList, error)
	CreateStoreSection(ctx context.Context, arg CreateStoreSectionParams) (StoreSection, error)
	CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error)
	CreateWeek(ctx context.Context, startsOn string) (Week, error)
	CreateWeekRecipe(ctx context.Context, arg CreateWeekRecipeParams) (WeekRecipe, error)
	DeleteGeneratedShoppingLines(ctx context.Context, shoppingListID int64) error
	DeleteWeekRecipe(ctx context.Context, id int64) (int64, error)
	DeleteWeekRecipes(ctx context.Context, weekID int64) error
	GetGroceryItemByKey(ctx context.Context, key string) (GroceryItem, error)
	GetOtherStoreSection(ctx context.Context) (StoreSection, error)
	GetRecipe(ctx context.Context, id int64) (Recipe, error)
	GetRecipeByKey(ctx context.Context, key string) (Recipe, error)
	GetShoppingListByWeek(ctx context.Context, weekID int64) (ShoppingList, error)
	GetStoreSectionByKey(ctx context.Context, key string) (StoreSection, error)
	GetUnitByKey(ctx context.Context, key string) (Unit, error)
	GetWeekByStart(ctx context.Context, startsOn string) (Week, error)
	GetWeekRecipe(ctx context.Context, id int64) (WeekRecipe, error)
	ListGeneratedShoppingLineStates(ctx context.Context, shoppingListID int64) ([]ListGeneratedShoppingLineStatesRow, error)
	ListGroceryItems(ctx context.Context) ([]ListGroceryItemsRow, error)
	ListIngredientSections(ctx context.Context, recipeID int64) ([]RecipeIngredientSection, error)
	ListInstructionSections(ctx context.Context, recipeID int64) ([]RecipeInstructionSection, error)
	ListRecipeIngredients(ctx context.Context, recipeID int64) ([]ListRecipeIngredientsRow, error)
	ListRecipeReviewFlags(ctx context.Context, recipeID int64) ([]RecipeReviewFlag, error)
	ListRecipeSources(ctx context.Context, recipeID int64) ([]RecipeSource, error)
	ListRecipeSteps(ctx context.Context, recipeID int64) ([]ListRecipeStepsRow, error)
	ListShoppingLineContributions(ctx context.Context, shoppingLineID int64) ([]ListShoppingLineContributionsRow, error)
	ListShoppingLines(ctx context.Context, shoppingListID int64) ([]ListShoppingLinesRow, error)
	ListStoreSections(ctx context.Context) ([]StoreSection, error)
	ListUnits(ctx context.Context) ([]Unit, error)
	ListVerifiedRecipes(ctx context.Context) ([]Recipe, error)
	ListWeekIngredientRequirements(ctx context.Context, weekID int64) ([]ListWeekIngredientRequirementsRow, error)
	ListWeekRecipeIDs(ctx context.Context, weekID int64) ([]int64, error)
	ListWeekRecipes(ctx context.Context, weekID int64) ([]ListWeekRecipesRow, error)
	MarkRecipeReviewable(ctx context.Context, id int64) (Recipe, error)
	NextManualShoppingLinePosition(ctx context.Context, shoppingListID int64) (int64, error)
	NextWeekRecipePosition(ctx context.Context, weekID int64) (int64, error)
	ReturnRecipeToDraft(ctx context.Context, id int64) (Recipe, error)
	SetShoppingLineCompleted(ctx context.Context, arg SetShoppingLineCompletedParams) (int64, error)
	SetShoppingLineOverride(ctx context.Context, arg SetShoppingLineOverrideParams) (int64, error)
	SetShoppingLineRemoved(ctx context.Context, arg SetShoppingLineRemovedParams) (int64, error)
	TouchWeek(ctx context.Context, id int64) error
	UpdateWeekRecipeRecipe(ctx context.Context, arg UpdateWeekRecipeRecipeParams) (WeekRecipe, error)
	VerifyRecipe(ctx context.Context, arg VerifyRecipeParams) (Recipe, error)
}

var _ Querier = (*Queries)(nil)
