// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shopping.sql

package store

import (
	"context"
	"database/sql"
)

const createGeneratedShoppingLine = `-- name: CreateGeneratedShoppingLine :one
INSERT INTO shopping_lines (
    shopping_list_id, grocery_item_id, store_section_id, aggregation_key,
    origin, display_name, quantity_kind,
    amount_min_numerator, amount_min_denominator,
    amount_max_numerator, amount_max_denominator, unit_id,
    package_type, package_size_numerator, package_size_denominator, package_size_unit_id,
    is_optional, is_removed, is_completed, display_position, override_text
) VALUES (?, ?, ?, ?, 'generated', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, shopping_list_id, grocery_item_id, store_section_id, aggregation_key, origin, display_name, quantity_kind, amount_min_numerator, amount_min_denominator, amount_max_numerator, amount_max_denominator, unit_id, package_type, package_size_numerator, package_size_denominator, package_size_unit_id, is_optional, is_removed, is_completed, display_position, override_text, created_at, updated_at
`

type CreateGeneratedShoppingLineParams struct {
	ShoppingListID         int64          `db:"shopping_list_id" json:"shopping_list_id"`
	GroceryItemID          sql.NullInt64  `db:"grocery_item_id" json:"grocery_item_id"`
	StoreSectionID         int64          `db:"store_section_id" json:"store_section_id"`
	AggregationKey         sql.NullString `db:"aggregation_key" json:"aggregation_key"`
	DisplayName            string         `db:"display_name" json:"display_name"`
	QuantityKind           string         `db:"quantity_kind" json:"quantity_kind"`
	AmountMinNumerator     sql.NullInt64  `db:"amount_min_numerator" json:"amount_min_numerator"`
	AmountMinDenominator   sql.NullInt64  `db:"amount_min_denominator" json:"amount_min_denominator"`
	AmountMaxNumerator     sql.NullInt64  `db:"amount_max_numerator" json:"amount_max_numerator"`
	AmountMaxDenominator   sql.NullInt64  `db:"amount_max_denominator" json:"amount_max_denominator"`
	UnitID                 sql.NullInt64  `db:"unit_id" json:"unit_id"`
	PackageType            sql.NullString `db:"package_type" json:"package_type"`
	PackageSizeNumerator   sql.NullInt64  `db:"package_size_numerator" json:"package_size_numerator"`
	PackageSizeDenominator sql.NullInt64  `db:"package_size_denominator" json:"package_size_denominator"`
	PackageSizeUnitID      sql.NullInt64  `db:"package_size_unit_id" json:"package_size_unit_id"`
	IsOptional             int64          `db:"is_optional" json:"is_optional"`
	IsRemoved              int64          `db:"is_removed" json:"is_removed"`
	IsCompleted            int64          `db:"is_completed" json:"is_completed"`
	DisplayPosition        int64          `db:"display_position" json:"display_position"`
	OverrideText           sql.NullString `db:"override_text" json:"override_text"`
}

func (q *Queries) CreateGeneratedShoppingLine(ctx context.Context, arg CreateGeneratedShoppingLineParams) (ShoppingLine, error) {
	row := q.db.QueryRowContext(ctx, createGeneratedShoppingLine,
		arg.ShoppingListID,
		arg.GroceryItemID,
		arg.StoreSectionID,
		arg.AggregationKey,
		arg.DisplayName,
		arg.QuantityKind,
		arg.AmountMinNumerator,
		arg.AmountMinDenominator,
		arg.AmountMaxNumerator,
		arg.AmountMaxDenominator,
		arg.UnitID,
		arg.PackageType,
		arg.PackageSizeNumerator,
		arg.PackageSizeDenominator,
		arg.PackageSizeUnitID,
		arg.IsOptional,
		arg.IsRemoved,
		arg.IsCompleted,
		arg.DisplayPosition,
		arg.OverrideText,
	)
	var i ShoppingLine
	err := row.Scan(
		&i.ID,
		&i.ShoppingListID,
		&i.GroceryItemID,
		&i.StoreSectionID,
		&i.AggregationKey,
		&i.Origin,
		&i.DisplayName,
		&i.QuantityKind,
		&i.AmountMinNumerator,
		&i.AmountMinDenominator,
		&i.AmountMaxNumerator,
		&i.AmountMaxDenominator,
		&i.UnitID,
		&i.PackageType,
		&i.PackageSizeNumerator,
		&i.PackageSizeDenominator,
		&i.PackageSizeUnitID,
		&i.IsOptional,
		&i.IsRemoved,
		&i.IsCompleted,
		&i.DisplayPosition,
		&i.OverrideText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManualShoppingLine = `-- name: CreateManualShoppingLine :one
INSERT INTO shopping_lines (
    shopping_list_id, store_section_id, origin, display_name, quantity_kind,
    display_position
) VALUES (?, ?, 'manual', ?, 'unspecified', ?)
RETURNING id, shopping_list_id, grocery_item_id, store_section_id, aggregation_key, origin, display_name, quantity_kind, amount_min_numerator, amount_min_denominator, amount_max_numerator, amount_max_denominator, unit_id, package_type, package_size_numerator, package_size_denominator, package_size_unit_id, is_optional, is_removed, is_completed, display_position, override_text, created_at, updated_at
`

type CreateManualShoppingLineParams struct {
	ShoppingListID  int64  `db:"shopping_list_id" json:"shopping_list_id"`
	StoreSectionID  int64  `db:"store_section_id" json:"store_section_id"`
	DisplayName     string `db:"display_name" json:"display_name"`
	DisplayPosition int64  `db:"display_position" json:"display_position"`
}

func (q *Queries) CreateManualShoppingLine(ctx context.Context, arg CreateManualShoppingLineParams) (ShoppingLine, error) {
	row := q.db.QueryRowContext(ctx, createManualShoppingLine,
		arg.ShoppingListID,
		arg.StoreSectionID,
		arg.DisplayName,
		arg.DisplayPosition,
	)
	var i ShoppingLine
	err := row.Scan(
		&i.ID,
		&i.ShoppingListID,
		&i.GroceryItemID,
		&i.StoreSectionID,
		&i.AggregationKey,
		&i.Origin,
		&i.DisplayName,
		&i.QuantityKind,
		&i.AmountMinNumerator,
		&i.AmountMinDenominator,
		&i.AmountMaxNumerator,
		&i.AmountMaxDenominator,
		&i.UnitID,
		&i.PackageType,
		&i.PackageSizeNumerator,
		&i.PackageSizeDenominator,
		&i.PackageSizeUnitID,
		&i.IsOptional,
		&i.IsRemoved,
		&i.IsCompleted,
		&i.DisplayPosition,
		&i.OverrideText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createShoppingLineContribution = `-- name: CreateShoppingLineContribution :one
INSERT INTO shopping_line_contributions (
    shopping_line_id, week_recipe_id, recipe_ingredient_id, quantity_kind,
    amount_min_numerator, amount_min_denominator,
    amount_max_numerator, amount_max_denominator, unit_id,
    package_type, package_size_numerator, package_size_denominator, package_size_unit_id,
    is_optional
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, shopping_line_id, week_recipe_id, recipe_ingredient_id, quantity_kind, amount_min_numerator, amount_min_denominator, amount_max_numerator, amount_max_denominator, unit_id, package_type, package_size_numerator, package_size_denominator, package_size_unit_id, is_optional
`

type CreateShoppingLineContributionParams struct {
	ShoppingLineID         int64          `db:"shopping_line_id" json:"shopping_line_id"`
	WeekRecipeID           int64          `db:"week_recipe_id" json:"week_recipe_id"`
	RecipeIngredientID     int64          `db:"recipe_ingredient_id" json:"recipe_ingredient_id"`
	QuantityKind           string         `db:"quantity_kind" json:"quantity_kind"`
	AmountMinNumerator     sql.NullInt64  `db:"amount_min_numerator" json:"amount_min_numerator"`
	AmountMinDenominator   sql.NullInt64  `db:"amount_min_denominator" json:"amount_min_denominator"`
	AmountMaxNumerator     sql.NullInt64  `db:"amount_max_numerator" json:"amount_max_numerator"`
	AmountMaxDenominator   sql.NullInt64  `db:"amount_max_denominator" json:"amount_max_denominator"`
	UnitID                 sql.NullInt64  `db:"unit_id" json:"unit_id"`
	PackageType            sql.NullString `db:"package_type" json:"package_type"`
	PackageSizeNumerator   sql.NullInt64  `db:"package_size_numerator" json:"package_size_numerator"`
	PackageSizeDenominator sql.NullInt64  `db:"package_size_denominator" json:"package_size_denominator"`
	PackageSizeUnitID      sql.NullInt64  `db:"package_size_unit_id" json:"package_size_unit_id"`
	IsOptional             int64          `db:"is_optional" json:"is_optional"`
}

func (q *Queries) CreateShoppingLineContribution(ctx context.Context, arg CreateShoppingLineContributionParams) (ShoppingLineContribution, error) {
	row := q.db.QueryRowContext(ctx, createShoppingLineContribution,
		arg.ShoppingLineID,
		arg.WeekRecipeID,
		arg.RecipeIngredientID,
		arg.QuantityKind,
		arg.AmountMinNumerator,
		arg.AmountMinDenominator,
		arg.AmountMaxNumerator,
		arg.AmountMaxDenominator,
		arg.UnitID,
		arg.PackageType,
		arg.PackageSizeNumerator,
		arg.PackageSizeDenominator,
		arg.PackageSizeUnitID,
		arg.IsOptional,
	)
	var i ShoppingLineContribution
	err := row.Scan(
		&i.ID,
		&i.ShoppingLineID,
		&i.WeekRecipeID,
		&i.RecipeIngredientID,
		&i.QuantityKind,
		&i.AmountMinNumerator,
		&i.AmountMinDenominator,
		&i.AmountMaxNumerator,
		&i.AmountMaxDenominator,
		&i.UnitID,
		&i.PackageType,
		&i.PackageSizeNumerator,
		&i.PackageSizeDenominator,
		&i.PackageSizeUnitID,
		&i.IsOptional,
	)
	return i, err
}

const deleteGeneratedShoppingLines = `-- name: DeleteGeneratedShoppingLines :exec
DELETE FROM shopping_lines WHERE shopping_list_id = ? AND origin = 'generated'
`

func (q *Queries) DeleteGeneratedShoppingLines(ctx context.Context, shoppingListID int64) error {
	_, err := q.db.ExecContext(ctx, deleteGeneratedShoppingLines, shoppingListID)
	return err
}

const getOtherStoreSection = `-- name: GetOtherStoreSection :one
SELECT id, "key", name FROM store_sections WHERE key = 'other'
`

func (q *Queries) GetOtherStoreSection(ctx context.Context) (StoreSection, error) {
	row := q.db.QueryRowContext(ctx, getOtherStoreSection)
	var i StoreSection
	err := row.Scan(&i.ID, &i.Key, &i.Name)
	return i, err
}

const listGeneratedShoppingLineStates = `-- name: ListGeneratedShoppingLineStates :many
SELECT id, aggregation_key, is_removed, is_completed, override_text
FROM shopping_lines
WHERE shopping_list_id = ? AND origin = 'generated'
`

type ListGeneratedShoppingLineStatesRow struct {
	ID             int64          `db:"id" json:"id"`
	AggregationKey sql.NullString `db:"aggregation_key" json:"aggregation_key"`
	IsRemoved      int64          `db:"is_removed" json:"is_removed"`
	IsCompleted    int64          `db:"is_completed" json:"is_completed"`
	OverrideText   sql.NullString `db:"override_text" json:"override_text"`
}

func (q *Queries) ListGeneratedShoppingLineStates(ctx context.Context, shoppingListID int64) ([]ListGeneratedShoppingLineStatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGeneratedShoppingLineStates, shoppingListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGeneratedShoppingLineStatesRow{}
	for rows.Next() {
		var i ListGeneratedShoppingLineStatesRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregationKey,
			&i.IsRemoved,
			&i.IsCompleted,
			&i.OverrideText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShoppingLineContributions = `-- name: ListShoppingLineContributions :many
SELECT c.id, c.shopping_line_id, c.week_recipe_id, c.recipe_ingredient_id, c.quantity_kind, c.amount_min_numerator, c.amount_min_denominator, c.amount_max_numerator, c.amount_max_denominator, c.unit_id, c.package_type, c.package_size_numerator, c.package_size_denominator, c.package_size_unit_id, c.is_optional, r.name AS recipe_name, ri.source_text, ri.preparation
FROM shopping_line_contributions c
JOIN week_recipes wr ON wr.id = c.week_recipe_id
JOIN recipes r ON r.id = wr.recipe_id
JOIN recipe_ingredients ri ON ri.id = c.recipe_ingredient_id
WHERE c.shopping_line_id = ?
ORDER BY wr.position, c.id
`

type ListShoppingLineContributionsRow struct {
	ID                     int64          `db:"id" json:"id"`
	ShoppingLineID         int64          `db:"shopping_line_id" json:"shopping_line_id"`
	WeekRecipeID           int64          `db:"week_recipe_id" json:"week_recipe_id"`
	RecipeIngredientID     int64          `db:"recipe_ingredient_id" json:"recipe_ingredient_id"`
	QuantityKind           string         `db:"quantity_kind" json:"quantity_kind"`
	AmountMinNumerator     sql.NullInt64  `db:"amount_min_numerator" json:"amount_min_numerator"`
	AmountMinDenominator   sql.NullInt64  `db:"amount_min_denominator" json:"amount_min_denominator"`
	AmountMaxNumerator     sql.NullInt64  `db:"amount_max_numerator" json:"amount_max_numerator"`
	AmountMaxDenominator   sql.NullInt64  `db:"amount_max_denominator" json:"amount_max_denominator"`
	UnitID                 sql.NullInt64  `db:"unit_id" json:"unit_id"`
	PackageType            sql.NullString `db:"package_type" json:"package_type"`
	PackageSizeNumerator   sql.NullInt64  `db:"package_size_numerator" json:"package_size_numerator"`
	PackageSizeDenominator sql.NullInt64  `db:"package_size_denominator" json:"package_size_denominator"`
	PackageSizeUnitID      sql.NullInt64  `db:"package_size_unit_id" json:"package_size_unit_id"`
	IsOptional             int64          `db:"is_optional" json:"is_optional"`
	RecipeName             string         `db:"recipe_name" json:"recipe_name"`
	SourceText             string         `db:"source_text" json:"source_text"`
	Preparation            sql.NullString `db:"preparation" json:"preparation"`
}

func (q *Queries) ListShoppingLineContributions(ctx context.Context, shoppingLineID int64) ([]ListShoppingLineContributionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listShoppingLineContributions, shoppingLineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShoppingLineContributionsRow{}
	for rows.Next() {
		var i ListShoppingLineContributionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingLineID,
			&i.WeekRecipeID,
			&i.RecipeIngredientID,
			&i.QuantityKind,
			&i.AmountMinNumerator,
			&i.AmountMinDenominator,
			&i.AmountMaxNumerator,
			&i.AmountMaxDenominator,
			&i.UnitID,
			&i.PackageType,
			&i.PackageSizeNumerator,
			&i.PackageSizeDenominator,
			&i.PackageSizeUnitID,
			&i.IsOptional,
			&i.RecipeName,
			&i.SourceText,
			&i.Preparation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShoppingLines = `-- name: ListShoppingLines :many
SELECT sl.id, sl.shopping_list_id, sl.grocery_item_id, sl.store_section_id, sl.aggregation_key, sl.origin, sl.display_name, sl.quantity_kind, sl.amount_min_numerator, sl.amount_min_denominator, sl.amount_max_numerator, sl.amount_max_denominator, sl.unit_id, sl.package_type, sl.package_size_numerator, sl.package_size_denominator, sl.package_size_unit_id, sl.is_optional, sl.is_removed, sl.is_completed, sl.display_position, sl.override_text, sl.created_at, sl.updated_at, ss.name AS store_section_name, u.key AS unit_key, psu.key AS package_size_unit_key
FROM shopping_lines sl
JOIN store_sections ss ON ss.id = sl.store_section_id
LEFT JOIN units u ON u.id = sl.unit_id
LEFT JOIN units psu ON psu.id = sl.package_size_unit_id
WHERE sl.shopping_list_id = ?
ORDER BY ss.name, sl.display_position, sl.display_name, sl.id
`

type ListShoppingLinesRow struct {
	ID                     int64          `db:"id" json:"id"`
	ShoppingListID         int64          `db:"shopping_list_id" json:"shopping_list_id"`
	GroceryItemID          sql.NullInt64  `db:"grocery_item_id" json:"grocery_item_id"`
	StoreSectionID         int64          `db:"store_section_id" json:"store_section_id"`
	AggregationKey         sql.NullString `db:"aggregation_key" json:"aggregation_key"`
	Origin                 string         `db:"origin" json:"origin"`
	DisplayName            string         `db:"display_name" json:"display_name"`
	QuantityKind           string         `db:"quantity_kind" json:"quantity_kind"`
	AmountMinNumerator     sql.NullInt64  `db:"amount_min_numerator" json:"amount_min_numerator"`
	AmountMinDenominator   sql.NullInt64  `db:"amount_min_denominator" json:"amount_min_denominator"`
	AmountMaxNumerator     sql.NullInt64  `db:"amount_max_numerator" json:"amount_max_numerator"`
	AmountMaxDenominator   sql.NullInt64  `db:"amount_max_denominator" json:"amount_max_denominator"`
	UnitID                 sql.NullInt64  `db:"unit_id" json:"unit_id"`
	PackageType            sql.NullString `db:"package_type" json:"package_type"`
	PackageSizeNumerator   sql.NullInt64  `db:"package_size_numerator" json:"package_size_numerator"`
	PackageSizeDenominator sql.NullInt64  `db:"package_size_denominator" json:"package_size_denominator"`
	PackageSizeUnitID      sql.NullInt64  `db:"package_size_unit_id" json:"package_size_unit_id"`
	IsOptional             int64          `db:"is_optional" json:"is_optional"`
	IsRemoved              int64          `db:"is_removed" json:"is_removed"`
	IsCompleted            int64          `db:"is_completed" json:"is_completed"`
	DisplayPosition        int64          `db:"display_position" json:"display_position"`
	OverrideText           sql.NullString `db:"override_text" json:"override_text"`
	CreatedAt              string         `db:"created_at" json:"created_at"`
	UpdatedAt              string         `db:"updated_at" json:"updated_at"`
	StoreSectionName       string         `db:"store_section_name" json:"store_section_name"`
	UnitKey                sql.NullString `db:"unit_key" json:"unit_key"`
	PackageSizeUnitKey     sql.NullString `db:"package_size_unit_key" json:"package_size_unit_key"`
}

func (q *Queries) ListShoppingLines(ctx context.Context, shoppingListID int64) ([]ListShoppingLinesRow, error) {
	rows, err := q.db.QueryContext(ctx, listShoppingLines, shoppingListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShoppingLinesRow{}
	for rows.Next() {
		var i ListShoppingLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingListID,
			&i.GroceryItemID,
			&i.StoreSectionID,
			&i.AggregationKey,
			&i.Origin,
			&i.DisplayName,
			&i.QuantityKind,
			&i.AmountMinNumerator,
			&i.AmountMinDenominator,
			&i.AmountMaxNumerator,
			&i.AmountMaxDenominator,
			&i.UnitID,
			&i.PackageType,
			&i.PackageSizeNumerator,
			&i.PackageSizeDenominator,
			&i.PackageSizeUnitID,
			&i.IsOptional,
			&i.IsRemoved,
			&i.IsCompleted,
			&i.DisplayPosition,
			&i.OverrideText,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StoreSectionName,
			&i.UnitKey,
			&i.PackageSizeUnitKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextManualShoppingLinePosition = `-- name: NextManualShoppingLinePosition :one
SELECT CAST(coalesce(max(display_position) + 1, 0) AS INTEGER)
FROM shopping_lines WHERE shopping_list_id = ? AND origin = 'manual'
`

func (q *Queries) NextManualShoppingLinePosition(ctx context.Context, shoppingListID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextManualShoppingLinePosition, shoppingListID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setShoppingLineCompleted = `-- name: SetShoppingLineCompleted :execrows
UPDATE shopping_lines
SET is_completed = ?1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE shopping_lines.id = ?2 AND shopping_list_id = (
    SELECT list.id FROM shopping_lists list
    JOIN weeks w ON w.id = list.week_id
    WHERE w.starts_on = ?3
)
`

type SetShoppingLineCompletedParams struct {
	Completed int64  `db:"completed" json:"completed"`
	LineID    int64  `db:"line_id" json:"line_id"`
	StartsOn  string `db:"starts_on" json:"starts_on"`
}

func (q *Queries) SetShoppingLineCompleted(ctx context.Context, arg SetShoppingLineCompletedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setShoppingLineCompleted, arg.Completed, arg.LineID, arg.StartsOn)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setShoppingLineOverride = `-- name: SetShoppingLineOverride :execrows
UPDATE shopping_lines
SET override_text = ?1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE shopping_lines.id = ?2 AND origin = 'generated' AND shopping_list_id = (
    SELECT list.id FROM shopping_lists list
    JOIN weeks w ON w.id = list.week_id
    WHERE w.starts_on = ?3
)
`

type SetShoppingLineOverrideParams struct {
	OverrideText sql.NullString `db:"override_text" json:"override_text"`
	LineID       int64          `db:"line_id" json:"line_id"`
	StartsOn     string         `db:"starts_on" json:"starts_on"`
}

func (q *Queries) SetShoppingLineOverride(ctx context.Context, arg SetShoppingLineOverrideParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setShoppingLineOverride, arg.OverrideText, arg.LineID, arg.StartsOn)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setShoppingLineRemoved = `-- name: SetShoppingLineRemoved :execrows
UPDATE shopping_lines
SET is_removed = ?1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE shopping_lines.id = ?2 AND shopping_list_id = (
    SELECT list.id FROM shopping_lists list
    JOIN weeks w ON w.id = list.week_id
    WHERE w.starts_on = ?3
)
`

type SetShoppingLineRemovedParams struct {
	Removed  int64  `db:"removed" json:"removed"`
	LineID   int64  `db:"line_id" json:"line_id"`
	StartsOn string `db:"starts_on" json:"starts_on"`
}

func (q *Queries) SetShoppingLineRemoved(ctx context.Context, arg SetShoppingLineRemovedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setShoppingLineRemoved, arg.Removed, arg.LineID, arg.StartsOn)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
