// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: week.sql

package store

import (
	"context"
	"database/sql"
)

const createShoppingList = `-- name: CreateShoppingList :one
INSERT INTO shopping_lists (week_id) VALUES (?)
RETURNING id, week_id, created_at, updated_at
`

func (q *Queries) CreateShoppingList(ctx context.Context, weekID int64) (ShoppingList, error) {
	row := q.db.QueryRowContext(ctx, createShoppingList, weekID)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWeek = `-- name: CreateWeek :one
INSERT INTO weeks (starts_on) VALUES (?)
RETURNING id, starts_on, created_at, updated_at
`

func (q *Queries) CreateWeek(ctx context.Context, startsOn string) (Week, error) {
	row := q.db.QueryRowContext(ctx, createWeek, startsOn)
	var i Week
	err := row.Scan(
		&i.ID,
		&i.StartsOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWeekRecipe = `-- name: CreateWeekRecipe :one
INSERT INTO week_recipes (week_id, recipe_id, position) VALUES (?, ?, ?)
RETURNING id, week_id, recipe_id, position, created_at
`

type CreateWeekRecipeParams struct {
	WeekID   int64 `db:"week_id" json:"week_id"`
	RecipeID int64 `db:"recipe_id" json:"recipe_id"`
	Position int64 `db:"position" json:"position"`
}

func (q *Queries) CreateWeekRecipe(ctx context.Context, arg CreateWeekRecipeParams) (WeekRecipe, error) {
	row := q.db.QueryRowContext(ctx, createWeekRecipe, arg.WeekID, arg.RecipeID, arg.Position)
	var i WeekRecipe
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.RecipeID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWeekRecipe = `-- name: DeleteWeekRecipe :execrows
DELETE FROM week_recipes WHERE id = ?
`

func (q *Queries) DeleteWeekRecipe(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWeekRecipe, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteWeekRecipes = `-- name: DeleteWeekRecipes :exec
DELETE FROM week_recipes WHERE week_id = ?
`

func (q *Queries) DeleteWeekRecipes(ctx context.Context, weekID int64) error {
	_, err := q.db.ExecContext(ctx, deleteWeekRecipes, weekID)
	return err
}

const getShoppingListByWeek = `-- name: GetShoppingListByWeek :one
SELECT id, week_id, created_at, updated_at FROM shopping_lists WHERE week_id = ?
`

func (q *Queries) GetShoppingListByWeek(ctx context.Context, weekID int64) (ShoppingList, error) {
	row := q.db.QueryRowContext(ctx, getShoppingListByWeek, weekID)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeekByStart = `-- name: GetWeekByStart :one
SELECT id, starts_on, created_at, updated_at FROM weeks WHERE starts_on = ?
`

func (q *Queries) GetWeekByStart(ctx context.Context, startsOn string) (Week, error) {
	row := q.db.QueryRowContext(ctx, getWeekByStart, startsOn)
	var i Week
	err := row.Scan(
		&i.ID,
		&i.StartsOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeekRecipe = `-- name: GetWeekRecipe :one
SELECT id, week_id, recipe_id, position, created_at FROM week_recipes WHERE id = ?
`

func (q *Queries) GetWeekRecipe(ctx context.Context, id int64) (WeekRecipe, error) {
	row := q.db.QueryRowContext(ctx, getWeekRecipe, id)
	var i WeekRecipe
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.RecipeID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listWeekIngredientRequirements = `-- name: ListWeekIngredientRequirements :many
SELECT
    wr.id AS week_recipe_id,
    wr.position AS week_recipe_position,
    r.id AS recipe_id,
    r.name AS recipe_name,
    ri.id AS recipe_ingredient_id,
    ri.position AS ingredient_position,
    ri.quantity_kind,
    ri.amount_min_numerator,
    ri.amount_min_denominator,
    ri.amount_max_numerator,
    ri.amount_max_denominator,
    ri.unit_id,
    ri.package_type,
    ri.package_size_numerator,
    ri.package_size_denominator,
    ri.package_size_unit_id,
    ri.preparation,
    ri.is_optional,
    gi.id AS grocery_item_id,
    gi.key AS grocery_item_key,
    gi.name AS grocery_item_name,
    gi.shopping_mode,
    ss.id AS store_section_id,
    ss.name AS store_section_name,
    u.key AS unit_key,
    u.dimension AS unit_dimension,
    u.to_base_numerator AS unit_to_base_numerator,
    u.to_base_denominator AS unit_to_base_denominator,
    psu.key AS package_size_unit_key
FROM week_recipes wr
JOIN recipes r ON r.id = wr.recipe_id
JOIN recipe_ingredient_sections ris ON ris.recipe_id = r.id
JOIN recipe_ingredients ri ON ri.section_id = ris.id
JOIN grocery_items gi ON gi.id = ri.grocery_item_id
JOIN store_sections ss ON ss.id = gi.store_section_id
LEFT JOIN units u ON u.id = ri.unit_id
LEFT JOIN units psu ON psu.id = ri.package_size_unit_id
WHERE wr.week_id = ? AND ri.include_on_grocery_list = 1
ORDER BY wr.position, wr.id, ris.position, ri.position
`

type ListWeekIngredientRequirementsRow struct {
	WeekRecipeID           int64          `db:"week_recipe_id" json:"week_recipe_id"`
	WeekRecipePosition     int64          `db:"week_recipe_position" json:"week_recipe_position"`
	RecipeID               int64          `db:"recipe_id" json:"recipe_id"`
	RecipeName             string         `db:"recipe_name" json:"recipe_name"`
	RecipeIngredientID     int64          `db:"recipe_ingredient_id" json:"recipe_ingredient_id"`
	IngredientPosition     int64          `db:"ingredient_position" json:"ingredient_position"`
	QuantityKind           string         `db:"quantity_kind" json:"quantity_kind"`
	AmountMinNumerator     sql.NullInt64  `db:"amount_min_numerator" json:"amount_min_numerator"`
	AmountMinDenominator   sql.NullInt64  `db:"amount_min_denominator" json:"amount_min_denominator"`
	AmountMaxNumerator     sql.NullInt64  `db:"amount_max_numerator" json:"amount_max_numerator"`
	AmountMaxDenominator   sql.NullInt64  `db:"amount_max_denominator" json:"amount_max_denominator"`
	UnitID                 sql.NullInt64  `db:"unit_id" json:"unit_id"`
	PackageType            sql.NullString `db:"package_type" json:"package_type"`
	PackageSizeNumerator   sql.NullInt64  `db:"package_size_numerator" json:"package_size_numerator"`
	PackageSizeDenominator sql.NullInt64  `db:"package_size_denominator" json:"package_size_denominator"`
	PackageSizeUnitID      sql.NullInt64  `db:"package_size_unit_id" json:"package_size_unit_id"`
	Preparation            sql.NullString `db:"preparation" json:"preparation"`
	IsOptional             int64          `db:"is_optional" json:"is_optional"`
	GroceryItemID          int64          `db:"grocery_item_id" json:"grocery_item_id"`
	GroceryItemKey         string         `db:"grocery_item_key" json:"grocery_item_key"`
	GroceryItemName        string         `db:"grocery_item_name" json:"grocery_item_name"`
	ShoppingMode           string         `db:"shopping_mode" json:"shopping_mode"`
	StoreSectionID         int64          `db:"store_section_id" json:"store_section_id"`
	StoreSectionName       string         `db:"store_section_name" json:"store_section_name"`
	UnitKey                sql.NullString `db:"unit_key" json:"unit_key"`
	UnitDimension          sql.NullString `db:"unit_dimension" json:"unit_dimension"`
	UnitToBaseNumerator    sql.NullInt64  `db:"unit_to_base_numerator" json:"unit_to_base_numerator"`
	UnitToBaseDenominator  sql.NullInt64  `db:"unit_to_base_denominator" json:"unit_to_base_denominator"`
	PackageSizeUnitKey     sql.NullString `db:"package_size_unit_key" json:"package_size_unit_key"`
}

func (q *Queries) ListWeekIngredientRequirements(ctx context.Context, weekID int64) ([]ListWeekIngredientRequirementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWeekIngredientRequirements, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWeekIngredientRequirementsRow{}
	for rows.Next() {
		var i ListWeekIngredientRequirementsRow
		if err := rows.Scan(
			&i.WeekRecipeID,
			&i.WeekRecipePosition,
			&i.RecipeID,
			&i.RecipeName,
			&i.RecipeIngredientID,
			&i.IngredientPosition,
			&i.QuantityKind,
			&i.AmountMinNumerator,
			&i.AmountMinDenominator,
			&i.AmountMaxNumerator,
			&i.AmountMaxDenominator,
			&i.UnitID,
			&i.PackageType,
			&i.PackageSizeNumerator,
			&i.PackageSizeDenominator,
			&i.PackageSizeUnitID,
			&i.Preparation,
			&i.IsOptional,
			&i.GroceryItemID,
			&i.GroceryItemKey,
			&i.GroceryItemName,
			&i.ShoppingMode,
			&i.StoreSectionID,
			&i.StoreSectionName,
			&i.UnitKey,
			&i.UnitDimension,
			&i.UnitToBaseNumerator,
			&i.UnitToBaseDenominator,
			&i.PackageSizeUnitKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeekRecipeIDs = `-- name: ListWeekRecipeIDs :many
SELECT recipe_id FROM week_recipes WHERE week_id = ?
`

func (q *Queries) ListWeekRecipeIDs(ctx context.Context, weekID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listWeekRecipeIDs, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var recipe_id int64
		if err := rows.Scan(&recipe_id); err != nil {
			return nil, err
		}
		items = append(items, recipe_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeekRecipes = `-- name: ListWeekRecipes :many
SELECT
    wr.id, wr.week_id, wr.recipe_id, wr.position, wr.created_at,
    r.key AS recipe_key,
    r.name AS recipe_name,
    r.image_url,
    r.yield_text,
    r.hands_on_min_minutes,
    r.hands_on_max_minutes,
    r.unattended_min_minutes,
    r.unattended_max_minutes
FROM week_recipes wr
JOIN recipes r ON r.id = wr.recipe_id
WHERE wr.week_id = ?
ORDER BY wr.position, wr.id
`

type ListWeekRecipesRow struct {
	ID                   int64          `db:"id" json:"id"`
	WeekID               int64          `db:"week_id" json:"week_id"`
	RecipeID             int64          `db:"recipe_id" json:"recipe_id"`
	Position             int64          `db:"position" json:"position"`
	CreatedAt            string         `db:"created_at" json:"created_at"`
	RecipeKey            string         `db:"recipe_key" json:"recipe_key"`
	RecipeName           string         `db:"recipe_name" json:"recipe_name"`
	ImageUrl             sql.NullString `db:"image_url" json:"image_url"`
	YieldText            sql.NullString `db:"yield_text" json:"yield_text"`
	HandsOnMinMinutes    sql.NullInt64  `db:"hands_on_min_minutes" json:"hands_on_min_minutes"`
	HandsOnMaxMinutes    sql.NullInt64  `db:"hands_on_max_minutes" json:"hands_on_max_minutes"`
	UnattendedMinMinutes sql.NullInt64  `db:"unattended_min_minutes" json:"unattended_min_minutes"`
	UnattendedMaxMinutes sql.NullInt64  `db:"unattended_max_minutes" json:"unattended_max_minutes"`
}

func (q *Queries) ListWeekRecipes(ctx context.Context, weekID int64) ([]ListWeekRecipesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWeekRecipes, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWeekRecipesRow{}
	for rows.Next() {
		var i ListWeekRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.WeekID,
			&i.RecipeID,
			&i.Position,
			&i.CreatedAt,
			&i.RecipeKey,
			&i.RecipeName,
			&i.ImageUrl,
			&i.YieldText,
			&i.HandsOnMinMinutes,
			&i.HandsOnMaxMinutes,
			&i.UnattendedMinMinutes,
			&i.UnattendedMaxMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextWeekRecipePosition = `-- name: NextWeekRecipePosition :one
SELECT CAST(coalesce(max(position) + 1, 0) AS INTEGER) FROM week_recipes WHERE week_id = ?
`

func (q *Queries) NextWeekRecipePosition(ctx context.Context, weekID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextWeekRecipePosition, weekID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const touchWeek = `-- name: TouchWeek :exec
UPDATE weeks SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = ?
`

func (q *Queries) TouchWeek(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchWeek, id)
	return err
}

const updateWeekRecipeRecipe = `-- name: UpdateWeekRecipeRecipe :one
UPDATE week_recipes SET recipe_id = ? WHERE id = ?
RETURNING id, week_id, recipe_id, position, created_at
`

type UpdateWeekRecipeRecipeParams struct {
	RecipeID int64 `db:"recipe_id" json:"recipe_id"`
	ID       int64 `db:"id" json:"id"`
}

func (q *Queries) UpdateWeekRecipeRecipe(ctx context.Context, arg UpdateWeekRecipeRecipeParams) (WeekRecipe, error) {
	row := q.db.QueryRowContext(ctx, updateWeekRecipeRecipe, arg.RecipeID, arg.ID)
	var i WeekRecipe
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.RecipeID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
