apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: service-nodeport.yaml
images:
  - name: grocery-router
    newName: ghcr.io/mbcoward3/grocery-router
    newTag: sha-0000000000000000000000000000000000000000
